// Code generated by ent, DO NOT EDIT.

package securityevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldLTE(FieldID, id))
}

// EventType applies equality check predicate on the "event_type" field. It's identical to EventTypeEQ.
func EventType(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEQ(FieldEventType, v))
}

// Severity applies equality check predicate on the "severity" field. It's identical to SeverityEQ.
func Severity(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEQ(FieldSeverity, v))
}

// Category applies equality check predicate on the "category" field. It's identical to CategoryEQ.
func Category(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEQ(FieldCategory, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEQ(FieldTitle, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEQ(FieldDescription, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEQ(FieldUserID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEQ(FieldAPIKeyID, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEQ(FieldRequestID, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEQ(FieldModel, v))
}

// Action applies equality check predicate on the "action" field. It's identical to ActionEQ.
func Action(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEQ(FieldAction, v))
}

// MatchedPatterns applies equality check predicate on the "matched_patterns" field. It's identical to MatchedPatternsEQ.
func MatchedPatterns(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEQ(FieldMatchedPatterns, v))
}

// Confidence applies equality check predicate on the "confidence" field. It's identical to ConfidenceEQ.
func Confidence(v float64) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEQ(FieldConfidence, v))
}

// RequestSnapshot applies equality check predicate on the "request_snapshot" field. It's identical to RequestSnapshotEQ.
func RequestSnapshot(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEQ(FieldRequestSnapshot, v))
}

// SourceIP applies equality check predicate on the "source_ip" field. It's identical to SourceIPEQ.
func SourceIP(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEQ(FieldSourceIP, v))
}

// UserAgent applies equality check predicate on the "user_agent" field. It's identical to UserAgentEQ.
func UserAgent(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEQ(FieldUserAgent, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEQ(FieldStatus, v))
}

// Resolution applies equality check predicate on the "resolution" field. It's identical to ResolutionEQ.
func Resolution(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEQ(FieldResolution, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// ResolvedAt applies equality check predicate on the "resolved_at" field. It's identical to ResolvedAtEQ.
func ResolvedAt(v time.Time) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEQ(FieldResolvedAt, v))
}

// EventTypeEQ applies the EQ predicate on the "event_type" field.
func EventTypeEQ(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEQ(FieldEventType, v))
}

// EventTypeNEQ applies the NEQ predicate on the "event_type" field.
func EventTypeNEQ(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNEQ(FieldEventType, v))
}

// EventTypeIn applies the In predicate on the "event_type" field.
func EventTypeIn(vs ...string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldIn(FieldEventType, vs...))
}

// EventTypeNotIn applies the NotIn predicate on the "event_type" field.
func EventTypeNotIn(vs ...string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNotIn(FieldEventType, vs...))
}

// EventTypeGT applies the GT predicate on the "event_type" field.
func EventTypeGT(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldGT(FieldEventType, v))
}

// EventTypeGTE applies the GTE predicate on the "event_type" field.
func EventTypeGTE(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldGTE(FieldEventType, v))
}

// EventTypeLT applies the LT predicate on the "event_type" field.
func EventTypeLT(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldLT(FieldEventType, v))
}

// EventTypeLTE applies the LTE predicate on the "event_type" field.
func EventTypeLTE(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldLTE(FieldEventType, v))
}

// EventTypeContains applies the Contains predicate on the "event_type" field.
func EventTypeContains(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldContains(FieldEventType, v))
}

// EventTypeHasPrefix applies the HasPrefix predicate on the "event_type" field.
func EventTypeHasPrefix(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldHasPrefix(FieldEventType, v))
}

// EventTypeHasSuffix applies the HasSuffix predicate on the "event_type" field.
func EventTypeHasSuffix(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldHasSuffix(FieldEventType, v))
}

// EventTypeEqualFold applies the EqualFold predicate on the "event_type" field.
func EventTypeEqualFold(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEqualFold(FieldEventType, v))
}

// EventTypeContainsFold applies the ContainsFold predicate on the "event_type" field.
func EventTypeContainsFold(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldContainsFold(FieldEventType, v))
}

// SeverityEQ applies the EQ predicate on the "severity" field.
func SeverityEQ(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEQ(FieldSeverity, v))
}

// SeverityNEQ applies the NEQ predicate on the "severity" field.
func SeverityNEQ(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNEQ(FieldSeverity, v))
}

// SeverityIn applies the In predicate on the "severity" field.
func SeverityIn(vs ...string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldIn(FieldSeverity, vs...))
}

// SeverityNotIn applies the NotIn predicate on the "severity" field.
func SeverityNotIn(vs ...string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNotIn(FieldSeverity, vs...))
}

// SeverityGT applies the GT predicate on the "severity" field.
func SeverityGT(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldGT(FieldSeverity, v))
}

// SeverityGTE applies the GTE predicate on the "severity" field.
func SeverityGTE(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldGTE(FieldSeverity, v))
}

// SeverityLT applies the LT predicate on the "severity" field.
func SeverityLT(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldLT(FieldSeverity, v))
}

// SeverityLTE applies the LTE predicate on the "severity" field.
func SeverityLTE(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldLTE(FieldSeverity, v))
}

// SeverityContains applies the Contains predicate on the "severity" field.
func SeverityContains(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldContains(FieldSeverity, v))
}

// SeverityHasPrefix applies the HasPrefix predicate on the "severity" field.
func SeverityHasPrefix(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldHasPrefix(FieldSeverity, v))
}

// SeverityHasSuffix applies the HasSuffix predicate on the "severity" field.
func SeverityHasSuffix(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldHasSuffix(FieldSeverity, v))
}

// SeverityEqualFold applies the EqualFold predicate on the "severity" field.
func SeverityEqualFold(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEqualFold(FieldSeverity, v))
}

// SeverityContainsFold applies the ContainsFold predicate on the "severity" field.
func SeverityContainsFold(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldContainsFold(FieldSeverity, v))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNotIn(FieldCategory, vs...))
}

// CategoryGT applies the GT predicate on the "category" field.
func CategoryGT(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldGT(FieldCategory, v))
}

// CategoryGTE applies the GTE predicate on the "category" field.
func CategoryGTE(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldGTE(FieldCategory, v))
}

// CategoryLT applies the LT predicate on the "category" field.
func CategoryLT(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldLT(FieldCategory, v))
}

// CategoryLTE applies the LTE predicate on the "category" field.
func CategoryLTE(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldLTE(FieldCategory, v))
}

// CategoryContains applies the Contains predicate on the "category" field.
func CategoryContains(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldContains(FieldCategory, v))
}

// CategoryHasPrefix applies the HasPrefix predicate on the "category" field.
func CategoryHasPrefix(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldHasPrefix(FieldCategory, v))
}

// CategoryHasSuffix applies the HasSuffix predicate on the "category" field.
func CategoryHasSuffix(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldHasSuffix(FieldCategory, v))
}

// CategoryEqualFold applies the EqualFold predicate on the "category" field.
func CategoryEqualFold(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEqualFold(FieldCategory, v))
}

// CategoryContainsFold applies the ContainsFold predicate on the "category" field.
func CategoryContainsFold(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldContainsFold(FieldCategory, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldContainsFold(FieldTitle, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldContainsFold(FieldDescription, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldLTE(FieldUserID, v))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNotNull(FieldUserID))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v int64) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v int64) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v int64) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v int64) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldLTE(FieldAPIKeyID, v))
}

// APIKeyIDIsNil applies the IsNil predicate on the "api_key_id" field.
func APIKeyIDIsNil() predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldIsNull(FieldAPIKeyID))
}

// APIKeyIDNotNil applies the NotNil predicate on the "api_key_id" field.
func APIKeyIDNotNil() predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNotNull(FieldAPIKeyID))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDIsNil applies the IsNil predicate on the "request_id" field.
func RequestIDIsNil() predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldIsNull(FieldRequestID))
}

// RequestIDNotNil applies the NotNil predicate on the "request_id" field.
func RequestIDNotNil() predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNotNull(FieldRequestID))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldContainsFold(FieldRequestID, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldHasSuffix(FieldModel, v))
}

// ModelIsNil applies the IsNil predicate on the "model" field.
func ModelIsNil() predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldIsNull(FieldModel))
}

// ModelNotNil applies the NotNil predicate on the "model" field.
func ModelNotNil() predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNotNull(FieldModel))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldContainsFold(FieldModel, v))
}

// ActionEQ applies the EQ predicate on the "action" field.
func ActionEQ(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEQ(FieldAction, v))
}

// ActionNEQ applies the NEQ predicate on the "action" field.
func ActionNEQ(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNEQ(FieldAction, v))
}

// ActionIn applies the In predicate on the "action" field.
func ActionIn(vs ...string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldIn(FieldAction, vs...))
}

// ActionNotIn applies the NotIn predicate on the "action" field.
func ActionNotIn(vs ...string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNotIn(FieldAction, vs...))
}

// ActionGT applies the GT predicate on the "action" field.
func ActionGT(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldGT(FieldAction, v))
}

// ActionGTE applies the GTE predicate on the "action" field.
func ActionGTE(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldGTE(FieldAction, v))
}

// ActionLT applies the LT predicate on the "action" field.
func ActionLT(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldLT(FieldAction, v))
}

// ActionLTE applies the LTE predicate on the "action" field.
func ActionLTE(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldLTE(FieldAction, v))
}

// ActionContains applies the Contains predicate on the "action" field.
func ActionContains(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldContains(FieldAction, v))
}

// ActionHasPrefix applies the HasPrefix predicate on the "action" field.
func ActionHasPrefix(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldHasPrefix(FieldAction, v))
}

// ActionHasSuffix applies the HasSuffix predicate on the "action" field.
func ActionHasSuffix(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldHasSuffix(FieldAction, v))
}

// ActionEqualFold applies the EqualFold predicate on the "action" field.
func ActionEqualFold(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEqualFold(FieldAction, v))
}

// ActionContainsFold applies the ContainsFold predicate on the "action" field.
func ActionContainsFold(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldContainsFold(FieldAction, v))
}

// MatchedPatternsEQ applies the EQ predicate on the "matched_patterns" field.
func MatchedPatternsEQ(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEQ(FieldMatchedPatterns, v))
}

// MatchedPatternsNEQ applies the NEQ predicate on the "matched_patterns" field.
func MatchedPatternsNEQ(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNEQ(FieldMatchedPatterns, v))
}

// MatchedPatternsIn applies the In predicate on the "matched_patterns" field.
func MatchedPatternsIn(vs ...string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldIn(FieldMatchedPatterns, vs...))
}

// MatchedPatternsNotIn applies the NotIn predicate on the "matched_patterns" field.
func MatchedPatternsNotIn(vs ...string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNotIn(FieldMatchedPatterns, vs...))
}

// MatchedPatternsGT applies the GT predicate on the "matched_patterns" field.
func MatchedPatternsGT(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldGT(FieldMatchedPatterns, v))
}

// MatchedPatternsGTE applies the GTE predicate on the "matched_patterns" field.
func MatchedPatternsGTE(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldGTE(FieldMatchedPatterns, v))
}

// MatchedPatternsLT applies the LT predicate on the "matched_patterns" field.
func MatchedPatternsLT(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldLT(FieldMatchedPatterns, v))
}

// MatchedPatternsLTE applies the LTE predicate on the "matched_patterns" field.
func MatchedPatternsLTE(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldLTE(FieldMatchedPatterns, v))
}

// MatchedPatternsContains applies the Contains predicate on the "matched_patterns" field.
func MatchedPatternsContains(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldContains(FieldMatchedPatterns, v))
}

// MatchedPatternsHasPrefix applies the HasPrefix predicate on the "matched_patterns" field.
func MatchedPatternsHasPrefix(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldHasPrefix(FieldMatchedPatterns, v))
}

// MatchedPatternsHasSuffix applies the HasSuffix predicate on the "matched_patterns" field.
func MatchedPatternsHasSuffix(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldHasSuffix(FieldMatchedPatterns, v))
}

// MatchedPatternsIsNil applies the IsNil predicate on the "matched_patterns" field.
func MatchedPatternsIsNil() predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldIsNull(FieldMatchedPatterns))
}

// MatchedPatternsNotNil applies the NotNil predicate on the "matched_patterns" field.
func MatchedPatternsNotNil() predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNotNull(FieldMatchedPatterns))
}

// MatchedPatternsEqualFold applies the EqualFold predicate on the "matched_patterns" field.
func MatchedPatternsEqualFold(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEqualFold(FieldMatchedPatterns, v))
}

// MatchedPatternsContainsFold applies the ContainsFold predicate on the "matched_patterns" field.
func MatchedPatternsContainsFold(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldContainsFold(FieldMatchedPatterns, v))
}

// ConfidenceEQ applies the EQ predicate on the "confidence" field.
func ConfidenceEQ(v float64) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEQ(FieldConfidence, v))
}

// ConfidenceNEQ applies the NEQ predicate on the "confidence" field.
func ConfidenceNEQ(v float64) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNEQ(FieldConfidence, v))
}

// ConfidenceIn applies the In predicate on the "confidence" field.
func ConfidenceIn(vs ...float64) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldIn(FieldConfidence, vs...))
}

// ConfidenceNotIn applies the NotIn predicate on the "confidence" field.
func ConfidenceNotIn(vs ...float64) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNotIn(FieldConfidence, vs...))
}

// ConfidenceGT applies the GT predicate on the "confidence" field.
func ConfidenceGT(v float64) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldGT(FieldConfidence, v))
}

// ConfidenceGTE applies the GTE predicate on the "confidence" field.
func ConfidenceGTE(v float64) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldGTE(FieldConfidence, v))
}

// ConfidenceLT applies the LT predicate on the "confidence" field.
func ConfidenceLT(v float64) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldLT(FieldConfidence, v))
}

// ConfidenceLTE applies the LTE predicate on the "confidence" field.
func ConfidenceLTE(v float64) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldLTE(FieldConfidence, v))
}

// RequestSnapshotEQ applies the EQ predicate on the "request_snapshot" field.
func RequestSnapshotEQ(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEQ(FieldRequestSnapshot, v))
}

// RequestSnapshotNEQ applies the NEQ predicate on the "request_snapshot" field.
func RequestSnapshotNEQ(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNEQ(FieldRequestSnapshot, v))
}

// RequestSnapshotIn applies the In predicate on the "request_snapshot" field.
func RequestSnapshotIn(vs ...string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldIn(FieldRequestSnapshot, vs...))
}

// RequestSnapshotNotIn applies the NotIn predicate on the "request_snapshot" field.
func RequestSnapshotNotIn(vs ...string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNotIn(FieldRequestSnapshot, vs...))
}

// RequestSnapshotGT applies the GT predicate on the "request_snapshot" field.
func RequestSnapshotGT(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldGT(FieldRequestSnapshot, v))
}

// RequestSnapshotGTE applies the GTE predicate on the "request_snapshot" field.
func RequestSnapshotGTE(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldGTE(FieldRequestSnapshot, v))
}

// RequestSnapshotLT applies the LT predicate on the "request_snapshot" field.
func RequestSnapshotLT(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldLT(FieldRequestSnapshot, v))
}

// RequestSnapshotLTE applies the LTE predicate on the "request_snapshot" field.
func RequestSnapshotLTE(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldLTE(FieldRequestSnapshot, v))
}

// RequestSnapshotContains applies the Contains predicate on the "request_snapshot" field.
func RequestSnapshotContains(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldContains(FieldRequestSnapshot, v))
}

// RequestSnapshotHasPrefix applies the HasPrefix predicate on the "request_snapshot" field.
func RequestSnapshotHasPrefix(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldHasPrefix(FieldRequestSnapshot, v))
}

// RequestSnapshotHasSuffix applies the HasSuffix predicate on the "request_snapshot" field.
func RequestSnapshotHasSuffix(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldHasSuffix(FieldRequestSnapshot, v))
}

// RequestSnapshotIsNil applies the IsNil predicate on the "request_snapshot" field.
func RequestSnapshotIsNil() predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldIsNull(FieldRequestSnapshot))
}

// RequestSnapshotNotNil applies the NotNil predicate on the "request_snapshot" field.
func RequestSnapshotNotNil() predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNotNull(FieldRequestSnapshot))
}

// RequestSnapshotEqualFold applies the EqualFold predicate on the "request_snapshot" field.
func RequestSnapshotEqualFold(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEqualFold(FieldRequestSnapshot, v))
}

// RequestSnapshotContainsFold applies the ContainsFold predicate on the "request_snapshot" field.
func RequestSnapshotContainsFold(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldContainsFold(FieldRequestSnapshot, v))
}

// SourceIPEQ applies the EQ predicate on the "source_ip" field.
func SourceIPEQ(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEQ(FieldSourceIP, v))
}

// SourceIPNEQ applies the NEQ predicate on the "source_ip" field.
func SourceIPNEQ(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNEQ(FieldSourceIP, v))
}

// SourceIPIn applies the In predicate on the "source_ip" field.
func SourceIPIn(vs ...string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldIn(FieldSourceIP, vs...))
}

// SourceIPNotIn applies the NotIn predicate on the "source_ip" field.
func SourceIPNotIn(vs ...string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNotIn(FieldSourceIP, vs...))
}

// SourceIPGT applies the GT predicate on the "source_ip" field.
func SourceIPGT(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldGT(FieldSourceIP, v))
}

// SourceIPGTE applies the GTE predicate on the "source_ip" field.
func SourceIPGTE(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldGTE(FieldSourceIP, v))
}

// SourceIPLT applies the LT predicate on the "source_ip" field.
func SourceIPLT(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldLT(FieldSourceIP, v))
}

// SourceIPLTE applies the LTE predicate on the "source_ip" field.
func SourceIPLTE(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldLTE(FieldSourceIP, v))
}

// SourceIPContains applies the Contains predicate on the "source_ip" field.
func SourceIPContains(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldContains(FieldSourceIP, v))
}

// SourceIPHasPrefix applies the HasPrefix predicate on the "source_ip" field.
func SourceIPHasPrefix(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldHasPrefix(FieldSourceIP, v))
}

// SourceIPHasSuffix applies the HasSuffix predicate on the "source_ip" field.
func SourceIPHasSuffix(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldHasSuffix(FieldSourceIP, v))
}

// SourceIPIsNil applies the IsNil predicate on the "source_ip" field.
func SourceIPIsNil() predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldIsNull(FieldSourceIP))
}

// SourceIPNotNil applies the NotNil predicate on the "source_ip" field.
func SourceIPNotNil() predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNotNull(FieldSourceIP))
}

// SourceIPEqualFold applies the EqualFold predicate on the "source_ip" field.
func SourceIPEqualFold(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEqualFold(FieldSourceIP, v))
}

// SourceIPContainsFold applies the ContainsFold predicate on the "source_ip" field.
func SourceIPContainsFold(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldContainsFold(FieldSourceIP, v))
}

// UserAgentEQ applies the EQ predicate on the "user_agent" field.
func UserAgentEQ(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEQ(FieldUserAgent, v))
}

// UserAgentNEQ applies the NEQ predicate on the "user_agent" field.
func UserAgentNEQ(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNEQ(FieldUserAgent, v))
}

// UserAgentIn applies the In predicate on the "user_agent" field.
func UserAgentIn(vs ...string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldIn(FieldUserAgent, vs...))
}

// UserAgentNotIn applies the NotIn predicate on the "user_agent" field.
func UserAgentNotIn(vs ...string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNotIn(FieldUserAgent, vs...))
}

// UserAgentGT applies the GT predicate on the "user_agent" field.
func UserAgentGT(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldGT(FieldUserAgent, v))
}

// UserAgentGTE applies the GTE predicate on the "user_agent" field.
func UserAgentGTE(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldGTE(FieldUserAgent, v))
}

// UserAgentLT applies the LT predicate on the "user_agent" field.
func UserAgentLT(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldLT(FieldUserAgent, v))
}

// UserAgentLTE applies the LTE predicate on the "user_agent" field.
func UserAgentLTE(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldLTE(FieldUserAgent, v))
}

// UserAgentContains applies the Contains predicate on the "user_agent" field.
func UserAgentContains(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldContains(FieldUserAgent, v))
}

// UserAgentHasPrefix applies the HasPrefix predicate on the "user_agent" field.
func UserAgentHasPrefix(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldHasPrefix(FieldUserAgent, v))
}

// UserAgentHasSuffix applies the HasSuffix predicate on the "user_agent" field.
func UserAgentHasSuffix(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldHasSuffix(FieldUserAgent, v))
}

// UserAgentIsNil applies the IsNil predicate on the "user_agent" field.
func UserAgentIsNil() predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldIsNull(FieldUserAgent))
}

// UserAgentNotNil applies the NotNil predicate on the "user_agent" field.
func UserAgentNotNil() predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNotNull(FieldUserAgent))
}

// UserAgentEqualFold applies the EqualFold predicate on the "user_agent" field.
func UserAgentEqualFold(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEqualFold(FieldUserAgent, v))
}

// UserAgentContainsFold applies the ContainsFold predicate on the "user_agent" field.
func UserAgentContainsFold(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldContainsFold(FieldUserAgent, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldContainsFold(FieldStatus, v))
}

// ResolutionEQ applies the EQ predicate on the "resolution" field.
func ResolutionEQ(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEQ(FieldResolution, v))
}

// ResolutionNEQ applies the NEQ predicate on the "resolution" field.
func ResolutionNEQ(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNEQ(FieldResolution, v))
}

// ResolutionIn applies the In predicate on the "resolution" field.
func ResolutionIn(vs ...string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldIn(FieldResolution, vs...))
}

// ResolutionNotIn applies the NotIn predicate on the "resolution" field.
func ResolutionNotIn(vs ...string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNotIn(FieldResolution, vs...))
}

// ResolutionGT applies the GT predicate on the "resolution" field.
func ResolutionGT(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldGT(FieldResolution, v))
}

// ResolutionGTE applies the GTE predicate on the "resolution" field.
func ResolutionGTE(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldGTE(FieldResolution, v))
}

// ResolutionLT applies the LT predicate on the "resolution" field.
func ResolutionLT(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldLT(FieldResolution, v))
}

// ResolutionLTE applies the LTE predicate on the "resolution" field.
func ResolutionLTE(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldLTE(FieldResolution, v))
}

// ResolutionContains applies the Contains predicate on the "resolution" field.
func ResolutionContains(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldContains(FieldResolution, v))
}

// ResolutionHasPrefix applies the HasPrefix predicate on the "resolution" field.
func ResolutionHasPrefix(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldHasPrefix(FieldResolution, v))
}

// ResolutionHasSuffix applies the HasSuffix predicate on the "resolution" field.
func ResolutionHasSuffix(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldHasSuffix(FieldResolution, v))
}

// ResolutionIsNil applies the IsNil predicate on the "resolution" field.
func ResolutionIsNil() predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldIsNull(FieldResolution))
}

// ResolutionNotNil applies the NotNil predicate on the "resolution" field.
func ResolutionNotNil() predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNotNull(FieldResolution))
}

// ResolutionEqualFold applies the EqualFold predicate on the "resolution" field.
func ResolutionEqualFold(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEqualFold(FieldResolution, v))
}

// ResolutionContainsFold applies the ContainsFold predicate on the "resolution" field.
func ResolutionContainsFold(v string) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldContainsFold(FieldResolution, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// ResolvedAtEQ applies the EQ predicate on the "resolved_at" field.
func ResolvedAtEQ(v time.Time) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldEQ(FieldResolvedAt, v))
}

// ResolvedAtNEQ applies the NEQ predicate on the "resolved_at" field.
func ResolvedAtNEQ(v time.Time) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNEQ(FieldResolvedAt, v))
}

// ResolvedAtIn applies the In predicate on the "resolved_at" field.
func ResolvedAtIn(vs ...time.Time) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldIn(FieldResolvedAt, vs...))
}

// ResolvedAtNotIn applies the NotIn predicate on the "resolved_at" field.
func ResolvedAtNotIn(vs ...time.Time) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNotIn(FieldResolvedAt, vs...))
}

// ResolvedAtGT applies the GT predicate on the "resolved_at" field.
func ResolvedAtGT(v time.Time) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldGT(FieldResolvedAt, v))
}

// ResolvedAtGTE applies the GTE predicate on the "resolved_at" field.
func ResolvedAtGTE(v time.Time) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldGTE(FieldResolvedAt, v))
}

// ResolvedAtLT applies the LT predicate on the "resolved_at" field.
func ResolvedAtLT(v time.Time) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldLT(FieldResolvedAt, v))
}

// ResolvedAtLTE applies the LTE predicate on the "resolved_at" field.
func ResolvedAtLTE(v time.Time) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldLTE(FieldResolvedAt, v))
}

// ResolvedAtIsNil applies the IsNil predicate on the "resolved_at" field.
func ResolvedAtIsNil() predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldIsNull(FieldResolvedAt))
}

// ResolvedAtNotNil applies the NotNil predicate on the "resolved_at" field.
func ResolvedAtNotNil() predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.FieldNotNull(FieldResolvedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SecurityEvent) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SecurityEvent) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SecurityEvent) predicate.SecurityEvent {
	return predicate.SecurityEvent(sql.NotPredicates(p))
}
