// Code generated by ent, DO NOT EDIT.

package auditlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the auditlog type in the database.
	Label = "audit_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldAction holds the string denoting the action field in the database.
	FieldAction = "action"
	// FieldResourceType holds the string denoting the resource_type field in the database.
	FieldResourceType = "resource_type"
	// FieldResourceID holds the string denoting the resource_id field in the database.
	FieldResourceID = "resource_id"
	// FieldActorIP holds the string denoting the actor_ip field in the database.
	FieldActorIP = "actor_ip"
	// FieldActorUserAgent holds the string denoting the actor_user_agent field in the database.
	FieldActorUserAgent = "actor_user_agent"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldSessionID holds the string denoting the session_id field in the database.
	FieldSessionID = "session_id"
	// FieldChanges holds the string denoting the changes field in the database.
	FieldChanges = "changes"
	// FieldResult holds the string denoting the result field in the database.
	FieldResult = "result"
	// FieldFailureReason holds the string denoting the failure_reason field in the database.
	FieldFailureReason = "failure_reason"
	// FieldPreviousHash holds the string denoting the previous_hash field in the database.
	FieldPreviousHash = "previous_hash"
	// FieldRecordHash holds the string denoting the record_hash field in the database.
	FieldRecordHash = "record_hash"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the auditlog in the database.
	Table = "audit_logs"
)

// Columns holds all SQL columns for auditlog fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldAPIKeyID,
	FieldAction,
	FieldResourceType,
	FieldResourceID,
	FieldActorIP,
	FieldActorUserAgent,
	FieldRequestID,
	FieldSessionID,
	FieldChanges,
	FieldResult,
	FieldFailureReason,
	FieldPreviousHash,
	FieldRecordHash,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ActionValidator is a validator for the "action" field. It is called by the builders before save.
	ActionValidator func(string) error
	// ResourceTypeValidator is a validator for the "resource_type" field. It is called by the builders before save.
	ResourceTypeValidator func(string) error
	// ResourceIDValidator is a validator for the "resource_id" field. It is called by the builders before save.
	ResourceIDValidator func(string) error
	// ActorIPValidator is a validator for the "actor_ip" field. It is called by the builders before save.
	ActorIPValidator func(string) error
	// ActorUserAgentValidator is a validator for the "actor_user_agent" field. It is called by the builders before save.
	ActorUserAgentValidator func(string) error
	// RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	RequestIDValidator func(string) error
	// SessionIDValidator is a validator for the "session_id" field. It is called by the builders before save.
	SessionIDValidator func(string) error
	// DefaultResult holds the default value on creation for the "result" field.
	DefaultResult string
	// ResultValidator is a validator for the "result" field. It is called by the builders before save.
	ResultValidator func(string) error
	// FailureReasonValidator is a validator for the "failure_reason" field. It is called by the builders before save.
	FailureReasonValidator func(string) error
	// PreviousHashValidator is a validator for the "previous_hash" field. It is called by the builders before save.
	PreviousHashValidator func(string) error
	// RecordHashValidator is a validator for the "record_hash" field. It is called by the builders before save.
	RecordHashValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the AuditLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByAction orders the results by the action field.
func ByAction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAction, opts...).ToFunc()
}

// ByResourceType orders the results by the resource_type field.
func ByResourceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceType, opts...).ToFunc()
}

// ByResourceID orders the results by the resource_id field.
func ByResourceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceID, opts...).ToFunc()
}

// ByActorIP orders the results by the actor_ip field.
func ByActorIP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActorIP, opts...).ToFunc()
}

// ByActorUserAgent orders the results by the actor_user_agent field.
func ByActorUserAgent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActorUserAgent, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// BySessionID orders the results by the session_id field.
func BySessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionID, opts...).ToFunc()
}

// ByChanges orders the results by the changes field.
func ByChanges(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChanges, opts...).ToFunc()
}

// ByResult orders the results by the result field.
func ByResult(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResult, opts...).ToFunc()
}

// ByFailureReason orders the results by the failure_reason field.
func ByFailureReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailureReason, opts...).ToFunc()
}

// ByPreviousHash orders the results by the previous_hash field.
func ByPreviousHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPreviousHash, opts...).ToFunc()
}

// ByRecordHash orders the results by the record_hash field.
func ByRecordHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecordHash, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
