// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/auditlog"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AuditLogUpdate is the builder for updating AuditLog entities.
type AuditLogUpdate struct {
	config
	hooks    []Hook
	mutation *AuditLogMutation
}

// Where appends a list predicates to the AuditLogUpdate builder.
func (_u *AuditLogUpdate) Where(ps ...predicate.AuditLog) *AuditLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AuditLogUpdate) SetUserID(v int64) *AuditLogUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableUserID(v *int64) *AuditLogUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *AuditLogUpdate) AddUserID(v int64) *AuditLogUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *AuditLogUpdate) ClearUserID() *AuditLogUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *AuditLogUpdate) SetAPIKeyID(v int64) *AuditLogUpdate {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableAPIKeyID(v *int64) *AuditLogUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *AuditLogUpdate) AddAPIKeyID(v int64) *AuditLogUpdate {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (_u *AuditLogUpdate) ClearAPIKeyID() *AuditLogUpdate {
	_u.mutation.ClearAPIKeyID()
	return _u
}

// SetAction sets the "action" field.
func (_u *AuditLogUpdate) SetAction(v string) *AuditLogUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableAction(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *AuditLogUpdate) SetResourceType(v string) *AuditLogUpdate {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableResourceType(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *AuditLogUpdate) SetResourceID(v string) *AuditLogUpdate {
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableResourceID(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// ClearResourceID clears the value of the "resource_id" field.
func (_u *AuditLogUpdate) ClearResourceID() *AuditLogUpdate {
	_u.mutation.ClearResourceID()
	return _u
}

// SetActorIP sets the "actor_ip" field.
func (_u *AuditLogUpdate) SetActorIP(v string) *AuditLogUpdate {
	_u.mutation.SetActorIP(v)
	return _u
}

// SetNillableActorIP sets the "actor_ip" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableActorIP(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetActorIP(*v)
	}
	return _u
}

// ClearActorIP clears the value of the "actor_ip" field.
func (_u *AuditLogUpdate) ClearActorIP() *AuditLogUpdate {
	_u.mutation.ClearActorIP()
	return _u
}

// SetActorUserAgent sets the "actor_user_agent" field.
func (_u *AuditLogUpdate) SetActorUserAgent(v string) *AuditLogUpdate {
	_u.mutation.SetActorUserAgent(v)
	return _u
}

// SetNillableActorUserAgent sets the "actor_user_agent" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableActorUserAgent(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetActorUserAgent(*v)
	}
	return _u
}

// ClearActorUserAgent clears the value of the "actor_user_agent" field.
func (_u *AuditLogUpdate) ClearActorUserAgent() *AuditLogUpdate {
	_u.mutation.ClearActorUserAgent()
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *AuditLogUpdate) SetRequestID(v string) *AuditLogUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableRequestID(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *AuditLogUpdate) ClearRequestID() *AuditLogUpdate {
	_u.mutation.ClearRequestID()
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *AuditLogUpdate) SetSessionID(v string) *AuditLogUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableSessionID(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// ClearSessionID clears the value of the "session_id" field.
func (_u *AuditLogUpdate) ClearSessionID() *AuditLogUpdate {
	_u.mutation.ClearSessionID()
	return _u
}

// SetChanges sets the "changes" field.
func (_u *AuditLogUpdate) SetChanges(v string) *AuditLogUpdate {
	_u.mutation.SetChanges(v)
	return _u
}

// SetNillableChanges sets the "changes" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableChanges(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetChanges(*v)
	}
	return _u
}

// ClearChanges clears the value of the "changes" field.
func (_u *AuditLogUpdate) ClearChanges() *AuditLogUpdate {
	_u.mutation.ClearChanges()
	return _u
}

// SetResult sets the "result" field.
func (_u *AuditLogUpdate) SetResult(v string) *AuditLogUpdate {
	_u.mutation.SetResult(v)
	return _u
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableResult(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetResult(*v)
	}
	return _u
}

// SetFailureReason sets the "failure_reason" field.
func (_u *AuditLogUpdate) SetFailureReason(v string) *AuditLogUpdate {
	_u.mutation.SetFailureReason(v)
	return _u
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableFailureReason(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetFailureReason(*v)
	}
	return _u
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (_u *AuditLogUpdate) ClearFailureReason() *AuditLogUpdate {
	_u.mutation.ClearFailureReason()
	return _u
}

// SetPreviousHash sets the "previous_hash" field.
func (_u *AuditLogUpdate) SetPreviousHash(v string) *AuditLogUpdate {
	_u.mutation.SetPreviousHash(v)
	return _u
}

// SetNillablePreviousHash sets the "previous_hash" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillablePreviousHash(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetPreviousHash(*v)
	}
	return _u
}

// ClearPreviousHash clears the value of the "previous_hash" field.
func (_u *AuditLogUpdate) ClearPreviousHash() *AuditLogUpdate {
	_u.mutation.ClearPreviousHash()
	return _u
}

// SetRecordHash sets the "record_hash" field.
func (_u *AuditLogUpdate) SetRecordHash(v string) *AuditLogUpdate {
	_u.mutation.SetRecordHash(v)
	return _u
}

// SetNillableRecordHash sets the "record_hash" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableRecordHash(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetRecordHash(*v)
	}
	return _u
}

// Mutation returns the AuditLogMutation object of the builder.
func (_u *AuditLogUpdate) Mutation() *AuditLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuditLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuditLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuditLogUpdate) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := auditlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "AuditLog.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceType(); ok {
		if err := auditlog.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "AuditLog.resource_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceID(); ok {
		if err := auditlog.ResourceIDValidator(v); err != nil {
			return &ValidationError{Name: "resource_id", err: fmt.Errorf(`ent: validator failed for field "AuditLog.resource_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActorIP(); ok {
		if err := auditlog.ActorIPValidator(v); err != nil {
			return &ValidationError{Name: "actor_ip", err: fmt.Errorf(`ent: validator failed for field "AuditLog.actor_ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActorUserAgent(); ok {
		if err := auditlog.ActorUserAgentValidator(v); err != nil {
			return &ValidationError{Name: "actor_user_agent", err: fmt.Errorf(`ent: validator failed for field "AuditLog.actor_user_agent": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := auditlog.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "AuditLog.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SessionID(); ok {
		if err := auditlog.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "AuditLog.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Result(); ok {
		if err := auditlog.ResultValidator(v); err != nil {
			return &ValidationError{Name: "result", err: fmt.Errorf(`ent: validator failed for field "AuditLog.result": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FailureReason(); ok {
		if err := auditlog.FailureReasonValidator(v); err != nil {
			return &ValidationError{Name: "failure_reason", err: fmt.Errorf(`ent: validator failed for field "AuditLog.failure_reason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PreviousHash(); ok {
		if err := auditlog.PreviousHashValidator(v); err != nil {
			return &ValidationError{Name: "previous_hash", err: fmt.Errorf(`ent: validator failed for field "AuditLog.previous_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RecordHash(); ok {
		if err := auditlog.RecordHashValidator(v); err != nil {
			return &ValidationError{Name: "record_hash", err: fmt.Errorf(`ent: validator failed for field "AuditLog.record_hash": %w`, err)}
		}
	}
	return nil
}

func (_u *AuditLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(auditlog.Table, auditlog.Columns, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(auditlog.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(auditlog.FieldUserID, field.TypeInt64, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(auditlog.FieldUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(auditlog.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(auditlog.FieldAPIKeyID, field.TypeInt64, value)
	}
	if _u.mutation.APIKeyIDCleared() {
		_spec.ClearField(auditlog.FieldAPIKeyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(auditlog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(auditlog.FieldResourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(auditlog.FieldResourceID, field.TypeString, value)
	}
	if _u.mutation.ResourceIDCleared() {
		_spec.ClearField(auditlog.FieldResourceID, field.TypeString)
	}
	if value, ok := _u.mutation.ActorIP(); ok {
		_spec.SetField(auditlog.FieldActorIP, field.TypeString, value)
	}
	if _u.mutation.ActorIPCleared() {
		_spec.ClearField(auditlog.FieldActorIP, field.TypeString)
	}
	if value, ok := _u.mutation.ActorUserAgent(); ok {
		_spec.SetField(auditlog.FieldActorUserAgent, field.TypeString, value)
	}
	if _u.mutation.ActorUserAgentCleared() {
		_spec.ClearField(auditlog.FieldActorUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(auditlog.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(auditlog.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(auditlog.FieldSessionID, field.TypeString, value)
	}
	if _u.mutation.SessionIDCleared() {
		_spec.ClearField(auditlog.FieldSessionID, field.TypeString)
	}
	if value, ok := _u.mutation.Changes(); ok {
		_spec.SetField(auditlog.FieldChanges, field.TypeString, value)
	}
	if _u.mutation.ChangesCleared() {
		_spec.ClearField(auditlog.FieldChanges, field.TypeString)
	}
	if value, ok := _u.mutation.Result(); ok {
		_spec.SetField(auditlog.FieldResult, field.TypeString, value)
	}
	if value, ok := _u.mutation.FailureReason(); ok {
		_spec.SetField(auditlog.FieldFailureReason, field.TypeString, value)
	}
	if _u.mutation.FailureReasonCleared() {
		_spec.ClearField(auditlog.FieldFailureReason, field.TypeString)
	}
	if value, ok := _u.mutation.PreviousHash(); ok {
		_spec.SetField(auditlog.FieldPreviousHash, field.TypeString, value)
	}
	if _u.mutation.PreviousHashCleared() {
		_spec.ClearField(auditlog.FieldPreviousHash, field.TypeString)
	}
	if value, ok := _u.mutation.RecordHash(); ok {
		_spec.SetField(auditlog.FieldRecordHash, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuditLogUpdateOne is the builder for updating a single AuditLog entity.
type AuditLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuditLogMutation
}

// SetUserID sets the "user_id" field.
func (_u *AuditLogUpdateOne) SetUserID(v int64) *AuditLogUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableUserID(v *int64) *AuditLogUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *AuditLogUpdateOne) AddUserID(v int64) *AuditLogUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *AuditLogUpdateOne) ClearUserID() *AuditLogUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *AuditLogUpdateOne) SetAPIKeyID(v int64) *AuditLogUpdateOne {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableAPIKeyID(v *int64) *AuditLogUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *AuditLogUpdateOne) AddAPIKeyID(v int64) *AuditLogUpdateOne {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (_u *AuditLogUpdateOne) ClearAPIKeyID() *AuditLogUpdateOne {
	_u.mutation.ClearAPIKeyID()
	return _u
}

// SetAction sets the "action" field.
func (_u *AuditLogUpdateOne) SetAction(v string) *AuditLogUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableAction(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *AuditLogUpdateOne) SetResourceType(v string) *AuditLogUpdateOne {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableResourceType(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *AuditLogUpdateOne) SetResourceID(v string) *AuditLogUpdateOne {
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableResourceID(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// ClearResourceID clears the value of the "resource_id" field.
func (_u *AuditLogUpdateOne) ClearResourceID() *AuditLogUpdateOne {
	_u.mutation.ClearResourceID()
	return _u
}

// SetActorIP sets the "actor_ip" field.
func (_u *AuditLogUpdateOne) SetActorIP(v string) *AuditLogUpdateOne {
	_u.mutation.SetActorIP(v)
	return _u
}

// SetNillableActorIP sets the "actor_ip" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableActorIP(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetActorIP(*v)
	}
	return _u
}

// ClearActorIP clears the value of the "actor_ip" field.
func (_u *AuditLogUpdateOne) ClearActorIP() *AuditLogUpdateOne {
	_u.mutation.ClearActorIP()
	return _u
}

// SetActorUserAgent sets the "actor_user_agent" field.
func (_u *AuditLogUpdateOne) SetActorUserAgent(v string) *AuditLogUpdateOne {
	_u.mutation.SetActorUserAgent(v)
	return _u
}

// SetNillableActorUserAgent sets the "actor_user_agent" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableActorUserAgent(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetActorUserAgent(*v)
	}
	return _u
}

// ClearActorUserAgent clears the value of the "actor_user_agent" field.
func (_u *AuditLogUpdateOne) ClearActorUserAgent() *AuditLogUpdateOne {
	_u.mutation.ClearActorUserAgent()
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *AuditLogUpdateOne) SetRequestID(v string) *AuditLogUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableRequestID(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *AuditLogUpdateOne) ClearRequestID() *AuditLogUpdateOne {
	_u.mutation.ClearRequestID()
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *AuditLogUpdateOne) SetSessionID(v string) *AuditLogUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableSessionID(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// ClearSessionID clears the value of the "session_id" field.
func (_u *AuditLogUpdateOne) ClearSessionID() *AuditLogUpdateOne {
	_u.mutation.ClearSessionID()
	return _u
}

// SetChanges sets the "changes" field.
func (_u *AuditLogUpdateOne) SetChanges(v string) *AuditLogUpdateOne {
	_u.mutation.SetChanges(v)
	return _u
}

// SetNillableChanges sets the "changes" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableChanges(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetChanges(*v)
	}
	return _u
}

// ClearChanges clears the value of the "changes" field.
func (_u *AuditLogUpdateOne) ClearChanges() *AuditLogUpdateOne {
	_u.mutation.ClearChanges()
	return _u
}

// SetResult sets the "result" field.
func (_u *AuditLogUpdateOne) SetResult(v string) *AuditLogUpdateOne {
	_u.mutation.SetResult(v)
	return _u
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableResult(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetResult(*v)
	}
	return _u
}

// SetFailureReason sets the "failure_reason" field.
func (_u *AuditLogUpdateOne) SetFailureReason(v string) *AuditLogUpdateOne {
	_u.mutation.SetFailureReason(v)
	return _u
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableFailureReason(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetFailureReason(*v)
	}
	return _u
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (_u *AuditLogUpdateOne) ClearFailureReason() *AuditLogUpdateOne {
	_u.mutation.ClearFailureReason()
	return _u
}

// SetPreviousHash sets the "previous_hash" field.
func (_u *AuditLogUpdateOne) SetPreviousHash(v string) *AuditLogUpdateOne {
	_u.mutation.SetPreviousHash(v)
	return _u
}

// SetNillablePreviousHash sets the "previous_hash" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillablePreviousHash(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetPreviousHash(*v)
	}
	return _u
}

// ClearPreviousHash clears the value of the "previous_hash" field.
func (_u *AuditLogUpdateOne) ClearPreviousHash() *AuditLogUpdateOne {
	_u.mutation.ClearPreviousHash()
	return _u
}

// SetRecordHash sets the "record_hash" field.
func (_u *AuditLogUpdateOne) SetRecordHash(v string) *AuditLogUpdateOne {
	_u.mutation.SetRecordHash(v)
	return _u
}

// SetNillableRecordHash sets the "record_hash" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableRecordHash(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetRecordHash(*v)
	}
	return _u
}

// Mutation returns the AuditLogMutation object of the builder.
func (_u *AuditLogUpdateOne) Mutation() *AuditLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the AuditLogUpdate builder.
func (_u *AuditLogUpdateOne) Where(ps ...predicate.AuditLog) *AuditLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuditLogUpdateOne) Select(field string, fields ...string) *AuditLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AuditLog entity.
func (_u *AuditLogUpdateOne) Save(ctx context.Context) (*AuditLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditLogUpdateOne) SaveX(ctx context.Context) *AuditLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuditLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuditLogUpdateOne) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := auditlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "AuditLog.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceType(); ok {
		if err := auditlog.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "AuditLog.resource_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceID(); ok {
		if err := auditlog.ResourceIDValidator(v); err != nil {
			return &ValidationError{Name: "resource_id", err: fmt.Errorf(`ent: validator failed for field "AuditLog.resource_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActorIP(); ok {
		if err := auditlog.ActorIPValidator(v); err != nil {
			return &ValidationError{Name: "actor_ip", err: fmt.Errorf(`ent: validator failed for field "AuditLog.actor_ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActorUserAgent(); ok {
		if err := auditlog.ActorUserAgentValidator(v); err != nil {
			return &ValidationError{Name: "actor_user_agent", err: fmt.Errorf(`ent: validator failed for field "AuditLog.actor_user_agent": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := auditlog.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "AuditLog.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SessionID(); ok {
		if err := auditlog.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "AuditLog.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Result(); ok {
		if err := auditlog.ResultValidator(v); err != nil {
			return &ValidationError{Name: "result", err: fmt.Errorf(`ent: validator failed for field "AuditLog.result": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FailureReason(); ok {
		if err := auditlog.FailureReasonValidator(v); err != nil {
			return &ValidationError{Name: "failure_reason", err: fmt.Errorf(`ent: validator failed for field "AuditLog.failure_reason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PreviousHash(); ok {
		if err := auditlog.PreviousHashValidator(v); err != nil {
			return &ValidationError{Name: "previous_hash", err: fmt.Errorf(`ent: validator failed for field "AuditLog.previous_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RecordHash(); ok {
		if err := auditlog.RecordHashValidator(v); err != nil {
			return &ValidationError{Name: "record_hash", err: fmt.Errorf(`ent: validator failed for field "AuditLog.record_hash": %w`, err)}
		}
	}
	return nil
}

func (_u *AuditLogUpdateOne) sqlSave(ctx context.Context) (_node *AuditLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(auditlog.Table, auditlog.Columns, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuditLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, auditlog.FieldID)
		for _, f := range fields {
			if !auditlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != auditlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(auditlog.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(auditlog.FieldUserID, field.TypeInt64, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(auditlog.FieldUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(auditlog.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(auditlog.FieldAPIKeyID, field.TypeInt64, value)
	}
	if _u.mutation.APIKeyIDCleared() {
		_spec.ClearField(auditlog.FieldAPIKeyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(auditlog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(auditlog.FieldResourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(auditlog.FieldResourceID, field.TypeString, value)
	}
	if _u.mutation.ResourceIDCleared() {
		_spec.ClearField(auditlog.FieldResourceID, field.TypeString)
	}
	if value, ok := _u.mutation.ActorIP(); ok {
		_spec.SetField(auditlog.FieldActorIP, field.TypeString, value)
	}
	if _u.mutation.ActorIPCleared() {
		_spec.ClearField(auditlog.FieldActorIP, field.TypeString)
	}
	if value, ok := _u.mutation.ActorUserAgent(); ok {
		_spec.SetField(auditlog.FieldActorUserAgent, field.TypeString, value)
	}
	if _u.mutation.ActorUserAgentCleared() {
		_spec.ClearField(auditlog.FieldActorUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(auditlog.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(auditlog.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(auditlog.FieldSessionID, field.TypeString, value)
	}
	if _u.mutation.SessionIDCleared() {
		_spec.ClearField(auditlog.FieldSessionID, field.TypeString)
	}
	if value, ok := _u.mutation.Changes(); ok {
		_spec.SetField(auditlog.FieldChanges, field.TypeString, value)
	}
	if _u.mutation.ChangesCleared() {
		_spec.ClearField(auditlog.FieldChanges, field.TypeString)
	}
	if value, ok := _u.mutation.Result(); ok {
		_spec.SetField(auditlog.FieldResult, field.TypeString, value)
	}
	if value, ok := _u.mutation.FailureReason(); ok {
		_spec.SetField(auditlog.FieldFailureReason, field.TypeString, value)
	}
	if _u.mutation.FailureReasonCleared() {
		_spec.ClearField(auditlog.FieldFailureReason, field.TypeString)
	}
	if value, ok := _u.mutation.PreviousHash(); ok {
		_spec.SetField(auditlog.FieldPreviousHash, field.TypeString, value)
	}
	if _u.mutation.PreviousHashCleared() {
		_spec.ClearField(auditlog.FieldPreviousHash, field.TypeString)
	}
	if value, ok := _u.mutation.RecordHash(); ok {
		_spec.SetField(auditlog.FieldRecordHash, field.TypeString, value)
	}
	_node = &AuditLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
