// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/auditlog"
)

// AuditLogCreate is the builder for creating a AuditLog entity.
type AuditLogCreate struct {
	config
	mutation *AuditLogMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *AuditLogCreate) SetUserID(v int64) *AuditLogCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableUserID(v *int64) *AuditLogCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *AuditLogCreate) SetAPIKeyID(v int64) *AuditLogCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableAPIKeyID(v *int64) *AuditLogCreate {
	if v != nil {
		_c.SetAPIKeyID(*v)
	}
	return _c
}

// SetAction sets the "action" field.
func (_c *AuditLogCreate) SetAction(v string) *AuditLogCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetResourceType sets the "resource_type" field.
func (_c *AuditLogCreate) SetResourceType(v string) *AuditLogCreate {
	_c.mutation.SetResourceType(v)
	return _c
}

// SetResourceID sets the "resource_id" field.
func (_c *AuditLogCreate) SetResourceID(v string) *AuditLogCreate {
	_c.mutation.SetResourceID(v)
	return _c
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableResourceID(v *string) *AuditLogCreate {
	if v != nil {
		_c.SetResourceID(*v)
	}
	return _c
}

// SetActorIP sets the "actor_ip" field.
func (_c *AuditLogCreate) SetActorIP(v string) *AuditLogCreate {
	_c.mutation.SetActorIP(v)
	return _c
}

// SetNillableActorIP sets the "actor_ip" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableActorIP(v *string) *AuditLogCreate {
	if v != nil {
		_c.SetActorIP(*v)
	}
	return _c
}

// SetActorUserAgent sets the "actor_user_agent" field.
func (_c *AuditLogCreate) SetActorUserAgent(v string) *AuditLogCreate {
	_c.mutation.SetActorUserAgent(v)
	return _c
}

// SetNillableActorUserAgent sets the "actor_user_agent" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableActorUserAgent(v *string) *AuditLogCreate {
	if v != nil {
		_c.SetActorUserAgent(*v)
	}
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *AuditLogCreate) SetRequestID(v string) *AuditLogCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableRequestID(v *string) *AuditLogCreate {
	if v != nil {
		_c.SetRequestID(*v)
	}
	return _c
}

// SetSessionID sets the "session_id" field.
func (_c *AuditLogCreate) SetSessionID(v string) *AuditLogCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableSessionID(v *string) *AuditLogCreate {
	if v != nil {
		_c.SetSessionID(*v)
	}
	return _c
}

// SetChanges sets the "changes" field.
func (_c *AuditLogCreate) SetChanges(v string) *AuditLogCreate {
	_c.mutation.SetChanges(v)
	return _c
}

// SetNillableChanges sets the "changes" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableChanges(v *string) *AuditLogCreate {
	if v != nil {
		_c.SetChanges(*v)
	}
	return _c
}

// SetResult sets the "result" field.
func (_c *AuditLogCreate) SetResult(v string) *AuditLogCreate {
	_c.mutation.SetResult(v)
	return _c
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableResult(v *string) *AuditLogCreate {
	if v != nil {
		_c.SetResult(*v)
	}
	return _c
}

// SetFailureReason sets the "failure_reason" field.
func (_c *AuditLogCreate) SetFailureReason(v string) *AuditLogCreate {
	_c.mutation.SetFailureReason(v)
	return _c
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableFailureReason(v *string) *AuditLogCreate {
	if v != nil {
		_c.SetFailureReason(*v)
	}
	return _c
}

// SetPreviousHash sets the "previous_hash" field.
func (_c *AuditLogCreate) SetPreviousHash(v string) *AuditLogCreate {
	_c.mutation.SetPreviousHash(v)
	return _c
}

// SetNillablePreviousHash sets the "previous_hash" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillablePreviousHash(v *string) *AuditLogCreate {
	if v != nil {
		_c.SetPreviousHash(*v)
	}
	return _c
}

// SetRecordHash sets the "record_hash" field.
func (_c *AuditLogCreate) SetRecordHash(v string) *AuditLogCreate {
	_c.mutation.SetRecordHash(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AuditLogCreate) SetCreatedAt(v time.Time) *AuditLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AuditLogCreate) SetNillableCreatedAt(v *time.Time) *AuditLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the AuditLogMutation object of the builder.
func (_c *AuditLogCreate) Mutation() *AuditLogMutation {
	return _c.mutation
}

// Save creates the AuditLog in the database.
func (_c *AuditLogCreate) Save(ctx context.Context) (*AuditLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuditLogCreate) SaveX(ctx context.Context) *AuditLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuditLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuditLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AuditLogCreate) defaults() {
	if _, ok := _c.mutation.Result(); !ok {
		v := auditlog.DefaultResult
		_c.mutation.SetResult(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := auditlog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuditLogCreate) check() error {
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "AuditLog.action"`)}
	}
	if v, ok := _c.mutation.Action(); ok {
		if err := auditlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "AuditLog.action": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ResourceType(); !ok {
		return &ValidationError{Name: "resource_type", err: errors.New(`ent: missing required field "AuditLog.resource_type"`)}
	}
	if v, ok := _c.mutation.ResourceType(); ok {
		if err := auditlog.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "AuditLog.resource_type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ResourceID(); ok {
		if err := auditlog.ResourceIDValidator(v); err != nil {
			return &ValidationError{Name: "resource_id", err: fmt.Errorf(`ent: validator failed for field "AuditLog.resource_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ActorIP(); ok {
		if err := auditlog.ActorIPValidator(v); err != nil {
			return &ValidationError{Name: "actor_ip", err: fmt.Errorf(`ent: validator failed for field "AuditLog.actor_ip": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ActorUserAgent(); ok {
		if err := auditlog.ActorUserAgentValidator(v); err != nil {
			return &ValidationError{Name: "actor_user_agent", err: fmt.Errorf(`ent: validator failed for field "AuditLog.actor_user_agent": %w`, err)}
		}
	}
	if v, ok := _c.mutation.RequestID(); ok {
		if err := auditlog.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "AuditLog.request_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.SessionID(); ok {
		if err := auditlog.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "AuditLog.session_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Result(); !ok {
		return &ValidationError{Name: "result", err: errors.New(`ent: missing required field "AuditLog.result"`)}
	}
	if v, ok := _c.mutation.Result(); ok {
		if err := auditlog.ResultValidator(v); err != nil {
			return &ValidationError{Name: "result", err: fmt.Errorf(`ent: validator failed for field "AuditLog.result": %w`, err)}
		}
	}
	if v, ok := _c.mutation.FailureReason(); ok {
		if err := auditlog.FailureReasonValidator(v); err != nil {
			return &ValidationError{Name: "failure_reason", err: fmt.Errorf(`ent: validator failed for field "AuditLog.failure_reason": %w`, err)}
		}
	}
	if v, ok := _c.mutation.PreviousHash(); ok {
		if err := auditlog.PreviousHashValidator(v); err != nil {
			return &ValidationError{Name: "previous_hash", err: fmt.Errorf(`ent: validator failed for field "AuditLog.previous_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RecordHash(); !ok {
		return &ValidationError{Name: "record_hash", err: errors.New(`ent: missing required field "AuditLog.record_hash"`)}
	}
	if v, ok := _c.mutation.RecordHash(); ok {
		if err := auditlog.RecordHashValidator(v); err != nil {
			return &ValidationError{Name: "record_hash", err: fmt.Errorf(`ent: validator failed for field "AuditLog.record_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AuditLog.created_at"`)}
	}
	return nil
}

func (_c *AuditLogCreate) sqlSave(ctx context.Context) (*AuditLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuditLogCreate) createSpec() (*AuditLog, *sqlgraph.CreateSpec) {
	var (
		_node = &AuditLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(auditlog.Table, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(auditlog.FieldUserID, field.TypeInt64, value)
		_node.UserID = &value
	}
	if value, ok := _c.mutation.APIKeyID(); ok {
		_spec.SetField(auditlog.FieldAPIKeyID, field.TypeInt64, value)
		_node.APIKeyID = &value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(auditlog.FieldAction, field.TypeString, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.ResourceType(); ok {
		_spec.SetField(auditlog.FieldResourceType, field.TypeString, value)
		_node.ResourceType = value
	}
	if value, ok := _c.mutation.ResourceID(); ok {
		_spec.SetField(auditlog.FieldResourceID, field.TypeString, value)
		_node.ResourceID = &value
	}
	if value, ok := _c.mutation.ActorIP(); ok {
		_spec.SetField(auditlog.FieldActorIP, field.TypeString, value)
		_node.ActorIP = &value
	}
	if value, ok := _c.mutation.ActorUserAgent(); ok {
		_spec.SetField(auditlog.FieldActorUserAgent, field.TypeString, value)
		_node.ActorUserAgent = &value
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(auditlog.FieldRequestID, field.TypeString, value)
		_node.RequestID = &value
	}
	if value, ok := _c.mutation.SessionID(); ok {
		_spec.SetField(auditlog.FieldSessionID, field.TypeString, value)
		_node.SessionID = &value
	}
	if value, ok := _c.mutation.Changes(); ok {
		_spec.SetField(auditlog.FieldChanges, field.TypeString, value)
		_node.Changes = &value
	}
	if value, ok := _c.mutation.Result(); ok {
		_spec.SetField(auditlog.FieldResult, field.TypeString, value)
		_node.Result = value
	}
	if value, ok := _c.mutation.FailureReason(); ok {
		_spec.SetField(auditlog.FieldFailureReason, field.TypeString, value)
		_node.FailureReason = &value
	}
	if value, ok := _c.mutation.PreviousHash(); ok {
		_spec.SetField(auditlog.FieldPreviousHash, field.TypeString, value)
		_node.PreviousHash = &value
	}
	if value, ok := _c.mutation.RecordHash(); ok {
		_spec.SetField(auditlog.FieldRecordHash, field.TypeString, value)
		_node.RecordHash = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(auditlog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AuditLog.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuditLogUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *AuditLogCreate) OnConflict(opts ...sql.ConflictOption) *AuditLogUpsertOne {
	_c.conflict = opts
	return &AuditLogUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AuditLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AuditLogCreate) OnConflictColumns(columns ...string) *AuditLogUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AuditLogUpsertOne{
		create: _c,
	}
}

type (
	// AuditLogUpsertOne is the builder for "upsert"-ing
	//  one AuditLog node.
	AuditLogUpsertOne struct {
		create *AuditLogCreate
	}

	// AuditLogUpsert is the "OnConflict" setter.
	AuditLogUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *AuditLogUpsert) SetUserID(v int64) *AuditLogUpsert {
	u.Set(auditlog.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AuditLogUpsert) UpdateUserID() *AuditLogUpsert {
	u.SetExcluded(auditlog.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *AuditLogUpsert) AddUserID(v int64) *AuditLogUpsert {
	u.Add(auditlog.FieldUserID, v)
	return u
}

// ClearUserID clears the value of the "user_id" field.
func (u *AuditLogUpsert) ClearUserID() *AuditLogUpsert {
	u.SetNull(auditlog.FieldUserID)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *AuditLogUpsert) SetAPIKeyID(v int64) *AuditLogUpsert {
	u.Set(auditlog.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *AuditLogUpsert) UpdateAPIKeyID() *AuditLogUpsert {
	u.SetExcluded(auditlog.FieldAPIKeyID)
	return u
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *AuditLogUpsert) AddAPIKeyID(v int64) *AuditLogUpsert {
	u.Add(auditlog.FieldAPIKeyID, v)
	return u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *AuditLogUpsert) ClearAPIKeyID() *AuditLogUpsert {
	u.SetNull(auditlog.FieldAPIKeyID)
	return u
}

// SetAction sets the "action" field.
func (u *AuditLogUpsert) SetAction(v string) *AuditLogUpsert {
	u.Set(auditlog.FieldAction, v)
	return u
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *AuditLogUpsert) UpdateAction() *AuditLogUpsert {
	u.SetExcluded(auditlog.FieldAction)
	return u
}

// SetResourceType sets the "resource_type" field.
func (u *AuditLogUpsert) SetResourceType(v string) *AuditLogUpsert {
	u.Set(auditlog.FieldResourceType, v)
	return u
}

// UpdateResourceType sets the "resource_type" field to the value that was provided on create.
func (u *AuditLogUpsert) UpdateResourceType() *AuditLogUpsert {
	u.SetExcluded(auditlog.FieldResourceType)
	return u
}

// SetResourceID sets the "resource_id" field.
func (u *AuditLogUpsert) SetResourceID(v string) *AuditLogUpsert {
	u.Set(auditlog.FieldResourceID, v)
	return u
}

// UpdateResourceID sets the "resource_id" field to the value that was provided on create.
func (u *AuditLogUpsert) UpdateResourceID() *AuditLogUpsert {
	u.SetExcluded(auditlog.FieldResourceID)
	return u
}

// ClearResourceID clears the value of the "resource_id" field.
func (u *AuditLogUpsert) ClearResourceID() *AuditLogUpsert {
	u.SetNull(auditlog.FieldResourceID)
	return u
}

// SetActorIP sets the "actor_ip" field.
func (u *AuditLogUpsert) SetActorIP(v string) *AuditLogUpsert {
	u.Set(auditlog.FieldActorIP, v)
	return u
}

// UpdateActorIP sets the "actor_ip" field to the value that was provided on create.
func (u *AuditLogUpsert) UpdateActorIP() *AuditLogUpsert {
	u.SetExcluded(auditlog.FieldActorIP)
	return u
}

// ClearActorIP clears the value of the "actor_ip" field.
func (u *AuditLogUpsert) ClearActorIP() *AuditLogUpsert {
	u.SetNull(auditlog.FieldActorIP)
	return u
}

// SetActorUserAgent sets the "actor_user_agent" field.
func (u *AuditLogUpsert) SetActorUserAgent(v string) *AuditLogUpsert {
	u.Set(auditlog.FieldActorUserAgent, v)
	return u
}

// UpdateActorUserAgent sets the "actor_user_agent" field to the value that was provided on create.
func (u *AuditLogUpsert) UpdateActorUserAgent() *AuditLogUpsert {
	u.SetExcluded(auditlog.FieldActorUserAgent)
	return u
}

// ClearActorUserAgent clears the value of the "actor_user_agent" field.
func (u *AuditLogUpsert) ClearActorUserAgent() *AuditLogUpsert {
	u.SetNull(auditlog.FieldActorUserAgent)
	return u
}

// SetRequestID sets the "request_id" field.
func (u *AuditLogUpsert) SetRequestID(v string) *AuditLogUpsert {
	u.Set(auditlog.FieldRequestID, v)
	return u
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *AuditLogUpsert) UpdateRequestID() *AuditLogUpsert {
	u.SetExcluded(auditlog.FieldRequestID)
	return u
}

// ClearRequestID clears the value of the "request_id" field.
func (u *AuditLogUpsert) ClearRequestID() *AuditLogUpsert {
	u.SetNull(auditlog.FieldRequestID)
	return u
}

// SetSessionID sets the "session_id" field.
func (u *AuditLogUpsert) SetSessionID(v string) *AuditLogUpsert {
	u.Set(auditlog.FieldSessionID, v)
	return u
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *AuditLogUpsert) UpdateSessionID() *AuditLogUpsert {
	u.SetExcluded(auditlog.FieldSessionID)
	return u
}

// ClearSessionID clears the value of the "session_id" field.
func (u *AuditLogUpsert) ClearSessionID() *AuditLogUpsert {
	u.SetNull(auditlog.FieldSessionID)
	return u
}

// SetChanges sets the "changes" field.
func (u *AuditLogUpsert) SetChanges(v string) *AuditLogUpsert {
	u.Set(auditlog.FieldChanges, v)
	return u
}

// UpdateChanges sets the "changes" field to the value that was provided on create.
func (u *AuditLogUpsert) UpdateChanges() *AuditLogUpsert {
	u.SetExcluded(auditlog.FieldChanges)
	return u
}

// ClearChanges clears the value of the "changes" field.
func (u *AuditLogUpsert) ClearChanges() *AuditLogUpsert {
	u.SetNull(auditlog.FieldChanges)
	return u
}

// SetResult sets the "result" field.
func (u *AuditLogUpsert) SetResult(v string) *AuditLogUpsert {
	u.Set(auditlog.FieldResult, v)
	return u
}

// UpdateResult sets the "result" field to the value that was provided on create.
func (u *AuditLogUpsert) UpdateResult() *AuditLogUpsert {
	u.SetExcluded(auditlog.FieldResult)
	return u
}

// SetFailureReason sets the "failure_reason" field.
func (u *AuditLogUpsert) SetFailureReason(v string) *AuditLogUpsert {
	u.Set(auditlog.FieldFailureReason, v)
	return u
}

// UpdateFailureReason sets the "failure_reason" field to the value that was provided on create.
func (u *AuditLogUpsert) UpdateFailureReason() *AuditLogUpsert {
	u.SetExcluded(auditlog.FieldFailureReason)
	return u
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (u *AuditLogUpsert) ClearFailureReason() *AuditLogUpsert {
	u.SetNull(auditlog.FieldFailureReason)
	return u
}

// SetPreviousHash sets the "previous_hash" field.
func (u *AuditLogUpsert) SetPreviousHash(v string) *AuditLogUpsert {
	u.Set(auditlog.FieldPreviousHash, v)
	return u
}

// UpdatePreviousHash sets the "previous_hash" field to the value that was provided on create.
func (u *AuditLogUpsert) UpdatePreviousHash() *AuditLogUpsert {
	u.SetExcluded(auditlog.FieldPreviousHash)
	return u
}

// ClearPreviousHash clears the value of the "previous_hash" field.
func (u *AuditLogUpsert) ClearPreviousHash() *AuditLogUpsert {
	u.SetNull(auditlog.FieldPreviousHash)
	return u
}

// SetRecordHash sets the "record_hash" field.
func (u *AuditLogUpsert) SetRecordHash(v string) *AuditLogUpsert {
	u.Set(auditlog.FieldRecordHash, v)
	return u
}

// UpdateRecordHash sets the "record_hash" field to the value that was provided on create.
func (u *AuditLogUpsert) UpdateRecordHash() *AuditLogUpsert {
	u.SetExcluded(auditlog.FieldRecordHash)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AuditLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AuditLogUpsertOne) UpdateNewValues() *AuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(auditlog.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AuditLog.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AuditLogUpsertOne) Ignore() *AuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuditLogUpsertOne) DoNothing() *AuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuditLogCreate.OnConflict
// documentation for more info.
func (u *AuditLogUpsertOne) Update(set func(*AuditLogUpsert)) *AuditLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuditLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *AuditLogUpsertOne) SetUserID(v int64) *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *AuditLogUpsertOne) AddUserID(v int64) *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AuditLogUpsertOne) UpdateUserID() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *AuditLogUpsertOne) ClearUserID() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *AuditLogUpsertOne) SetAPIKeyID(v int64) *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *AuditLogUpsertOne) AddAPIKeyID(v int64) *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *AuditLogUpsertOne) UpdateAPIKeyID() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateAPIKeyID()
	})
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *AuditLogUpsertOne) ClearAPIKeyID() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearAPIKeyID()
	})
}

// SetAction sets the "action" field.
func (u *AuditLogUpsertOne) SetAction(v string) *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *AuditLogUpsertOne) UpdateAction() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateAction()
	})
}

// SetResourceType sets the "resource_type" field.
func (u *AuditLogUpsertOne) SetResourceType(v string) *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetResourceType(v)
	})
}

// UpdateResourceType sets the "resource_type" field to the value that was provided on create.
func (u *AuditLogUpsertOne) UpdateResourceType() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateResourceType()
	})
}

// SetResourceID sets the "resource_id" field.
func (u *AuditLogUpsertOne) SetResourceID(v string) *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetResourceID(v)
	})
}

// UpdateResourceID sets the "resource_id" field to the value that was provided on create.
func (u *AuditLogUpsertOne) UpdateResourceID() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateResourceID()
	})
}

// ClearResourceID clears the value of the "resource_id" field.
func (u *AuditLogUpsertOne) ClearResourceID() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearResourceID()
	})
}

// SetActorIP sets the "actor_ip" field.
func (u *AuditLogUpsertOne) SetActorIP(v string) *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetActorIP(v)
	})
}

// UpdateActorIP sets the "actor_ip" field to the value that was provided on create.
func (u *AuditLogUpsertOne) UpdateActorIP() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateActorIP()
	})
}

// ClearActorIP clears the value of the "actor_ip" field.
func (u *AuditLogUpsertOne) ClearActorIP() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearActorIP()
	})
}

// SetActorUserAgent sets the "actor_user_agent" field.
func (u *AuditLogUpsertOne) SetActorUserAgent(v string) *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetActorUserAgent(v)
	})
}

// UpdateActorUserAgent sets the "actor_user_agent" field to the value that was provided on create.
func (u *AuditLogUpsertOne) UpdateActorUserAgent() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateActorUserAgent()
	})
}

// ClearActorUserAgent clears the value of the "actor_user_agent" field.
func (u *AuditLogUpsertOne) ClearActorUserAgent() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearActorUserAgent()
	})
}

// SetRequestID sets the "request_id" field.
func (u *AuditLogUpsertOne) SetRequestID(v string) *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *AuditLogUpsertOne) UpdateRequestID() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateRequestID()
	})
}

// ClearRequestID clears the value of the "request_id" field.
func (u *AuditLogUpsertOne) ClearRequestID() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearRequestID()
	})
}

// SetSessionID sets the "session_id" field.
func (u *AuditLogUpsertOne) SetSessionID(v string) *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetSessionID(v)
	})
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *AuditLogUpsertOne) UpdateSessionID() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateSessionID()
	})
}

// ClearSessionID clears the value of the "session_id" field.
func (u *AuditLogUpsertOne) ClearSessionID() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearSessionID()
	})
}

// SetChanges sets the "changes" field.
func (u *AuditLogUpsertOne) SetChanges(v string) *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetChanges(v)
	})
}

// UpdateChanges sets the "changes" field to the value that was provided on create.
func (u *AuditLogUpsertOne) UpdateChanges() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateChanges()
	})
}

// ClearChanges clears the value of the "changes" field.
func (u *AuditLogUpsertOne) ClearChanges() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearChanges()
	})
}

// SetResult sets the "result" field.
func (u *AuditLogUpsertOne) SetResult(v string) *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetResult(v)
	})
}

// UpdateResult sets the "result" field to the value that was provided on create.
func (u *AuditLogUpsertOne) UpdateResult() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateResult()
	})
}

// SetFailureReason sets the "failure_reason" field.
func (u *AuditLogUpsertOne) SetFailureReason(v string) *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetFailureReason(v)
	})
}

// UpdateFailureReason sets the "failure_reason" field to the value that was provided on create.
func (u *AuditLogUpsertOne) UpdateFailureReason() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateFailureReason()
	})
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (u *AuditLogUpsertOne) ClearFailureReason() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearFailureReason()
	})
}

// SetPreviousHash sets the "previous_hash" field.
func (u *AuditLogUpsertOne) SetPreviousHash(v string) *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetPreviousHash(v)
	})
}

// UpdatePreviousHash sets the "previous_hash" field to the value that was provided on create.
func (u *AuditLogUpsertOne) UpdatePreviousHash() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdatePreviousHash()
	})
}

// ClearPreviousHash clears the value of the "previous_hash" field.
func (u *AuditLogUpsertOne) ClearPreviousHash() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearPreviousHash()
	})
}

// SetRecordHash sets the "record_hash" field.
func (u *AuditLogUpsertOne) SetRecordHash(v string) *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetRecordHash(v)
	})
}

// UpdateRecordHash sets the "record_hash" field to the value that was provided on create.
func (u *AuditLogUpsertOne) UpdateRecordHash() *AuditLogUpsertOne {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateRecordHash()
	})
}

// Exec executes the query.
func (u *AuditLogUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuditLogCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuditLogUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AuditLogUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AuditLogUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AuditLogCreateBulk is the builder for creating many AuditLog entities in bulk.
type AuditLogCreateBulk struct {
	config
	err      error
	builders []*AuditLogCreate
	conflict []sql.ConflictOption
}

// Save creates the AuditLog entities in the database.
func (_c *AuditLogCreateBulk) Save(ctx context.Context) ([]*AuditLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AuditLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuditLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuditLogCreateBulk) SaveX(ctx context.Context) []*AuditLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuditLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuditLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AuditLog.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuditLogUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *AuditLogCreateBulk) OnConflict(opts ...sql.ConflictOption) *AuditLogUpsertBulk {
	_c.conflict = opts
	return &AuditLogUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AuditLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AuditLogCreateBulk) OnConflictColumns(columns ...string) *AuditLogUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AuditLogUpsertBulk{
		create: _c,
	}
}

// AuditLogUpsertBulk is the builder for "upsert"-ing
// a bulk of AuditLog nodes.
type AuditLogUpsertBulk struct {
	create *AuditLogCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AuditLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AuditLogUpsertBulk) UpdateNewValues() *AuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(auditlog.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AuditLog.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AuditLogUpsertBulk) Ignore() *AuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuditLogUpsertBulk) DoNothing() *AuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuditLogCreateBulk.OnConflict
// documentation for more info.
func (u *AuditLogUpsertBulk) Update(set func(*AuditLogUpsert)) *AuditLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuditLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *AuditLogUpsertBulk) SetUserID(v int64) *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *AuditLogUpsertBulk) AddUserID(v int64) *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *AuditLogUpsertBulk) UpdateUserID() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *AuditLogUpsertBulk) ClearUserID() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *AuditLogUpsertBulk) SetAPIKeyID(v int64) *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *AuditLogUpsertBulk) AddAPIKeyID(v int64) *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *AuditLogUpsertBulk) UpdateAPIKeyID() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateAPIKeyID()
	})
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *AuditLogUpsertBulk) ClearAPIKeyID() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearAPIKeyID()
	})
}

// SetAction sets the "action" field.
func (u *AuditLogUpsertBulk) SetAction(v string) *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *AuditLogUpsertBulk) UpdateAction() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateAction()
	})
}

// SetResourceType sets the "resource_type" field.
func (u *AuditLogUpsertBulk) SetResourceType(v string) *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetResourceType(v)
	})
}

// UpdateResourceType sets the "resource_type" field to the value that was provided on create.
func (u *AuditLogUpsertBulk) UpdateResourceType() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateResourceType()
	})
}

// SetResourceID sets the "resource_id" field.
func (u *AuditLogUpsertBulk) SetResourceID(v string) *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetResourceID(v)
	})
}

// UpdateResourceID sets the "resource_id" field to the value that was provided on create.
func (u *AuditLogUpsertBulk) UpdateResourceID() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateResourceID()
	})
}

// ClearResourceID clears the value of the "resource_id" field.
func (u *AuditLogUpsertBulk) ClearResourceID() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearResourceID()
	})
}

// SetActorIP sets the "actor_ip" field.
func (u *AuditLogUpsertBulk) SetActorIP(v string) *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetActorIP(v)
	})
}

// UpdateActorIP sets the "actor_ip" field to the value that was provided on create.
func (u *AuditLogUpsertBulk) UpdateActorIP() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateActorIP()
	})
}

// ClearActorIP clears the value of the "actor_ip" field.
func (u *AuditLogUpsertBulk) ClearActorIP() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearActorIP()
	})
}

// SetActorUserAgent sets the "actor_user_agent" field.
func (u *AuditLogUpsertBulk) SetActorUserAgent(v string) *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetActorUserAgent(v)
	})
}

// UpdateActorUserAgent sets the "actor_user_agent" field to the value that was provided on create.
func (u *AuditLogUpsertBulk) UpdateActorUserAgent() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateActorUserAgent()
	})
}

// ClearActorUserAgent clears the value of the "actor_user_agent" field.
func (u *AuditLogUpsertBulk) ClearActorUserAgent() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearActorUserAgent()
	})
}

// SetRequestID sets the "request_id" field.
func (u *AuditLogUpsertBulk) SetRequestID(v string) *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *AuditLogUpsertBulk) UpdateRequestID() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateRequestID()
	})
}

// ClearRequestID clears the value of the "request_id" field.
func (u *AuditLogUpsertBulk) ClearRequestID() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearRequestID()
	})
}

// SetSessionID sets the "session_id" field.
func (u *AuditLogUpsertBulk) SetSessionID(v string) *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetSessionID(v)
	})
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *AuditLogUpsertBulk) UpdateSessionID() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateSessionID()
	})
}

// ClearSessionID clears the value of the "session_id" field.
func (u *AuditLogUpsertBulk) ClearSessionID() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearSessionID()
	})
}

// SetChanges sets the "changes" field.
func (u *AuditLogUpsertBulk) SetChanges(v string) *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetChanges(v)
	})
}

// UpdateChanges sets the "changes" field to the value that was provided on create.
func (u *AuditLogUpsertBulk) UpdateChanges() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateChanges()
	})
}

// ClearChanges clears the value of the "changes" field.
func (u *AuditLogUpsertBulk) ClearChanges() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearChanges()
	})
}

// SetResult sets the "result" field.
func (u *AuditLogUpsertBulk) SetResult(v string) *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetResult(v)
	})
}

// UpdateResult sets the "result" field to the value that was provided on create.
func (u *AuditLogUpsertBulk) UpdateResult() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateResult()
	})
}

// SetFailureReason sets the "failure_reason" field.
func (u *AuditLogUpsertBulk) SetFailureReason(v string) *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetFailureReason(v)
	})
}

// UpdateFailureReason sets the "failure_reason" field to the value that was provided on create.
func (u *AuditLogUpsertBulk) UpdateFailureReason() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateFailureReason()
	})
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (u *AuditLogUpsertBulk) ClearFailureReason() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearFailureReason()
	})
}

// SetPreviousHash sets the "previous_hash" field.
func (u *AuditLogUpsertBulk) SetPreviousHash(v string) *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetPreviousHash(v)
	})
}

// UpdatePreviousHash sets the "previous_hash" field to the value that was provided on create.
func (u *AuditLogUpsertBulk) UpdatePreviousHash() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdatePreviousHash()
	})
}

// ClearPreviousHash clears the value of the "previous_hash" field.
func (u *AuditLogUpsertBulk) ClearPreviousHash() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.ClearPreviousHash()
	})
}

// SetRecordHash sets the "record_hash" field.
func (u *AuditLogUpsertBulk) SetRecordHash(v string) *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.SetRecordHash(v)
	})
}

// UpdateRecordHash sets the "record_hash" field to the value that was provided on create.
func (u *AuditLogUpsertBulk) UpdateRecordHash() *AuditLogUpsertBulk {
	return u.Update(func(s *AuditLogUpsert) {
		s.UpdateRecordHash()
	})
}

// Exec executes the query.
func (u *AuditLogUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AuditLogCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuditLogCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuditLogUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
