// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/dlprule"
)

// DLPRuleCreate is the builder for creating a DLPRule entity.
type DLPRuleCreate struct {
	config
	mutation *DLPRuleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *DLPRuleCreate) SetName(v string) *DLPRuleCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *DLPRuleCreate) SetDescription(v string) *DLPRuleCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetCategory sets the "category" field.
func (_c *DLPRuleCreate) SetCategory(v string) *DLPRuleCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetPattern sets the "pattern" field.
func (_c *DLPRuleCreate) SetPattern(v string) *DLPRuleCreate {
	_c.mutation.SetPattern(v)
	return _c
}

// SetPatternType sets the "pattern_type" field.
func (_c *DLPRuleCreate) SetPatternType(v string) *DLPRuleCreate {
	_c.mutation.SetPatternType(v)
	return _c
}

// SetNillablePatternType sets the "pattern_type" field if the given value is not nil.
func (_c *DLPRuleCreate) SetNillablePatternType(v *string) *DLPRuleCreate {
	if v != nil {
		_c.SetPatternType(*v)
	}
	return _c
}

// SetSeverity sets the "severity" field.
func (_c *DLPRuleCreate) SetSeverity(v string) *DLPRuleCreate {
	_c.mutation.SetSeverity(v)
	return _c
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (_c *DLPRuleCreate) SetNillableSeverity(v *string) *DLPRuleCreate {
	if v != nil {
		_c.SetSeverity(*v)
	}
	return _c
}

// SetAction sets the "action" field.
func (_c *DLPRuleCreate) SetAction(v string) *DLPRuleCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_c *DLPRuleCreate) SetNillableAction(v *string) *DLPRuleCreate {
	if v != nil {
		_c.SetAction(*v)
	}
	return _c
}

// SetMaskContent sets the "mask_content" field.
func (_c *DLPRuleCreate) SetMaskContent(v bool) *DLPRuleCreate {
	_c.mutation.SetMaskContent(v)
	return _c
}

// SetNillableMaskContent sets the "mask_content" field if the given value is not nil.
func (_c *DLPRuleCreate) SetNillableMaskContent(v *bool) *DLPRuleCreate {
	if v != nil {
		_c.SetMaskContent(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *DLPRuleCreate) SetEnabled(v bool) *DLPRuleCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *DLPRuleCreate) SetNillableEnabled(v *bool) *DLPRuleCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetPriority sets the "priority" field.
func (_c *DLPRuleCreate) SetPriority(v int) *DLPRuleCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *DLPRuleCreate) SetNillablePriority(v *int) *DLPRuleCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetScope sets the "scope" field.
func (_c *DLPRuleCreate) SetScope(v string) *DLPRuleCreate {
	_c.mutation.SetScope(v)
	return _c
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_c *DLPRuleCreate) SetNillableScope(v *string) *DLPRuleCreate {
	if v != nil {
		_c.SetScope(*v)
	}
	return _c
}

// SetModels sets the "models" field.
func (_c *DLPRuleCreate) SetModels(v string) *DLPRuleCreate {
	_c.mutation.SetModels(v)
	return _c
}

// SetNillableModels sets the "models" field if the given value is not nil.
func (_c *DLPRuleCreate) SetNillableModels(v *string) *DLPRuleCreate {
	if v != nil {
		_c.SetModels(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *DLPRuleCreate) SetMetadata(v string) *DLPRuleCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetNillableMetadata sets the "metadata" field if the given value is not nil.
func (_c *DLPRuleCreate) SetNillableMetadata(v *string) *DLPRuleCreate {
	if v != nil {
		_c.SetMetadata(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *DLPRuleCreate) SetCreatedBy(v int64) *DLPRuleCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *DLPRuleCreate) SetNillableCreatedBy(v *int64) *DLPRuleCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DLPRuleCreate) SetCreatedAt(v time.Time) *DLPRuleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DLPRuleCreate) SetNillableCreatedAt(v *time.Time) *DLPRuleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DLPRuleCreate) SetUpdatedAt(v time.Time) *DLPRuleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DLPRuleCreate) SetNillableUpdatedAt(v *time.Time) *DLPRuleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the DLPRuleMutation object of the builder.
func (_c *DLPRuleCreate) Mutation() *DLPRuleMutation {
	return _c.mutation
}

// Save creates the DLPRule in the database.
func (_c *DLPRuleCreate) Save(ctx context.Context) (*DLPRule, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DLPRuleCreate) SaveX(ctx context.Context) *DLPRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DLPRuleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DLPRuleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DLPRuleCreate) defaults() {
	if _, ok := _c.mutation.PatternType(); !ok {
		v := dlprule.DefaultPatternType
		_c.mutation.SetPatternType(v)
	}
	if _, ok := _c.mutation.Severity(); !ok {
		v := dlprule.DefaultSeverity
		_c.mutation.SetSeverity(v)
	}
	if _, ok := _c.mutation.Action(); !ok {
		v := dlprule.DefaultAction
		_c.mutation.SetAction(v)
	}
	if _, ok := _c.mutation.MaskContent(); !ok {
		v := dlprule.DefaultMaskContent
		_c.mutation.SetMaskContent(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := dlprule.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := dlprule.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.Scope(); !ok {
		v := dlprule.DefaultScope
		_c.mutation.SetScope(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := dlprule.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := dlprule.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DLPRuleCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "DLPRule.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := dlprule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DLPRule.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "DLPRule.description"`)}
	}
	if _, ok := _c.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "DLPRule.category"`)}
	}
	if v, ok := _c.mutation.Category(); ok {
		if err := dlprule.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "DLPRule.category": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Pattern(); !ok {
		return &ValidationError{Name: "pattern", err: errors.New(`ent: missing required field "DLPRule.pattern"`)}
	}
	if v, ok := _c.mutation.Pattern(); ok {
		if err := dlprule.PatternValidator(v); err != nil {
			return &ValidationError{Name: "pattern", err: fmt.Errorf(`ent: validator failed for field "DLPRule.pattern": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PatternType(); !ok {
		return &ValidationError{Name: "pattern_type", err: errors.New(`ent: missing required field "DLPRule.pattern_type"`)}
	}
	if v, ok := _c.mutation.PatternType(); ok {
		if err := dlprule.PatternTypeValidator(v); err != nil {
			return &ValidationError{Name: "pattern_type", err: fmt.Errorf(`ent: validator failed for field "DLPRule.pattern_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Severity(); !ok {
		return &ValidationError{Name: "severity", err: errors.New(`ent: missing required field "DLPRule.severity"`)}
	}
	if v, ok := _c.mutation.Severity(); ok {
		if err := dlprule.SeverityValidator(v); err != nil {
			return &ValidationError{Name: "severity", err: fmt.Errorf(`ent: validator failed for field "DLPRule.severity": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "DLPRule.action"`)}
	}
	if v, ok := _c.mutation.Action(); ok {
		if err := dlprule.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "DLPRule.action": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MaskContent(); !ok {
		return &ValidationError{Name: "mask_content", err: errors.New(`ent: missing required field "DLPRule.mask_content"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "DLPRule.enabled"`)}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "DLPRule.priority"`)}
	}
	if _, ok := _c.mutation.Scope(); !ok {
		return &ValidationError{Name: "scope", err: errors.New(`ent: missing required field "DLPRule.scope"`)}
	}
	if v, ok := _c.mutation.Scope(); ok {
		if err := dlprule.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "DLPRule.scope": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DLPRule.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DLPRule.updated_at"`)}
	}
	return nil
}

func (_c *DLPRuleCreate) sqlSave(ctx context.Context) (*DLPRule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DLPRuleCreate) createSpec() (*DLPRule, *sqlgraph.CreateSpec) {
	var (
		_node = &DLPRule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(dlprule.Table, sqlgraph.NewFieldSpec(dlprule.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(dlprule.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(dlprule.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(dlprule.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.Pattern(); ok {
		_spec.SetField(dlprule.FieldPattern, field.TypeString, value)
		_node.Pattern = value
	}
	if value, ok := _c.mutation.PatternType(); ok {
		_spec.SetField(dlprule.FieldPatternType, field.TypeString, value)
		_node.PatternType = value
	}
	if value, ok := _c.mutation.Severity(); ok {
		_spec.SetField(dlprule.FieldSeverity, field.TypeString, value)
		_node.Severity = value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(dlprule.FieldAction, field.TypeString, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.MaskContent(); ok {
		_spec.SetField(dlprule.FieldMaskContent, field.TypeBool, value)
		_node.MaskContent = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(dlprule.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(dlprule.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.Scope(); ok {
		_spec.SetField(dlprule.FieldScope, field.TypeString, value)
		_node.Scope = value
	}
	if value, ok := _c.mutation.Models(); ok {
		_spec.SetField(dlprule.FieldModels, field.TypeString, value)
		_node.Models = &value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(dlprule.FieldMetadata, field.TypeString, value)
		_node.Metadata = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(dlprule.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(dlprule.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(dlprule.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DLPRule.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DLPRuleUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *DLPRuleCreate) OnConflict(opts ...sql.ConflictOption) *DLPRuleUpsertOne {
	_c.conflict = opts
	return &DLPRuleUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DLPRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DLPRuleCreate) OnConflictColumns(columns ...string) *DLPRuleUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DLPRuleUpsertOne{
		create: _c,
	}
}

type (
	// DLPRuleUpsertOne is the builder for "upsert"-ing
	//  one DLPRule node.
	DLPRuleUpsertOne struct {
		create *DLPRuleCreate
	}

	// DLPRuleUpsert is the "OnConflict" setter.
	DLPRuleUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *DLPRuleUpsert) SetName(v string) *DLPRuleUpsert {
	u.Set(dlprule.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *DLPRuleUpsert) UpdateName() *DLPRuleUpsert {
	u.SetExcluded(dlprule.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *DLPRuleUpsert) SetDescription(v string) *DLPRuleUpsert {
	u.Set(dlprule.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *DLPRuleUpsert) UpdateDescription() *DLPRuleUpsert {
	u.SetExcluded(dlprule.FieldDescription)
	return u
}

// SetCategory sets the "category" field.
func (u *DLPRuleUpsert) SetCategory(v string) *DLPRuleUpsert {
	u.Set(dlprule.FieldCategory, v)
	return u
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *DLPRuleUpsert) UpdateCategory() *DLPRuleUpsert {
	u.SetExcluded(dlprule.FieldCategory)
	return u
}

// SetPattern sets the "pattern" field.
func (u *DLPRuleUpsert) SetPattern(v string) *DLPRuleUpsert {
	u.Set(dlprule.FieldPattern, v)
	return u
}

// UpdatePattern sets the "pattern" field to the value that was provided on create.
func (u *DLPRuleUpsert) UpdatePattern() *DLPRuleUpsert {
	u.SetExcluded(dlprule.FieldPattern)
	return u
}

// SetPatternType sets the "pattern_type" field.
func (u *DLPRuleUpsert) SetPatternType(v string) *DLPRuleUpsert {
	u.Set(dlprule.FieldPatternType, v)
	return u
}

// UpdatePatternType sets the "pattern_type" field to the value that was provided on create.
func (u *DLPRuleUpsert) UpdatePatternType() *DLPRuleUpsert {
	u.SetExcluded(dlprule.FieldPatternType)
	return u
}

// SetSeverity sets the "severity" field.
func (u *DLPRuleUpsert) SetSeverity(v string) *DLPRuleUpsert {
	u.Set(dlprule.FieldSeverity, v)
	return u
}

// UpdateSeverity sets the "severity" field to the value that was provided on create.
func (u *DLPRuleUpsert) UpdateSeverity() *DLPRuleUpsert {
	u.SetExcluded(dlprule.FieldSeverity)
	return u
}

// SetAction sets the "action" field.
func (u *DLPRuleUpsert) SetAction(v string) *DLPRuleUpsert {
	u.Set(dlprule.FieldAction, v)
	return u
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *DLPRuleUpsert) UpdateAction() *DLPRuleUpsert {
	u.SetExcluded(dlprule.FieldAction)
	return u
}

// SetMaskContent sets the "mask_content" field.
func (u *DLPRuleUpsert) SetMaskContent(v bool) *DLPRuleUpsert {
	u.Set(dlprule.FieldMaskContent, v)
	return u
}

// UpdateMaskContent sets the "mask_content" field to the value that was provided on create.
func (u *DLPRuleUpsert) UpdateMaskContent() *DLPRuleUpsert {
	u.SetExcluded(dlprule.FieldMaskContent)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *DLPRuleUpsert) SetEnabled(v bool) *DLPRuleUpsert {
	u.Set(dlprule.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *DLPRuleUpsert) UpdateEnabled() *DLPRuleUpsert {
	u.SetExcluded(dlprule.FieldEnabled)
	return u
}

// SetPriority sets the "priority" field.
func (u *DLPRuleUpsert) SetPriority(v int) *DLPRuleUpsert {
	u.Set(dlprule.FieldPriority, v)
	return u
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *DLPRuleUpsert) UpdatePriority() *DLPRuleUpsert {
	u.SetExcluded(dlprule.FieldPriority)
	return u
}

// AddPriority adds v to the "priority" field.
func (u *DLPRuleUpsert) AddPriority(v int) *DLPRuleUpsert {
	u.Add(dlprule.FieldPriority, v)
	return u
}

// SetScope sets the "scope" field.
func (u *DLPRuleUpsert) SetScope(v string) *DLPRuleUpsert {
	u.Set(dlprule.FieldScope, v)
	return u
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *DLPRuleUpsert) UpdateScope() *DLPRuleUpsert {
	u.SetExcluded(dlprule.FieldScope)
	return u
}

// SetModels sets the "models" field.
func (u *DLPRuleUpsert) SetModels(v string) *DLPRuleUpsert {
	u.Set(dlprule.FieldModels, v)
	return u
}

// UpdateModels sets the "models" field to the value that was provided on create.
func (u *DLPRuleUpsert) UpdateModels() *DLPRuleUpsert {
	u.SetExcluded(dlprule.FieldModels)
	return u
}

// ClearModels clears the value of the "models" field.
func (u *DLPRuleUpsert) ClearModels() *DLPRuleUpsert {
	u.SetNull(dlprule.FieldModels)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *DLPRuleUpsert) SetMetadata(v string) *DLPRuleUpsert {
	u.Set(dlprule.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *DLPRuleUpsert) UpdateMetadata() *DLPRuleUpsert {
	u.SetExcluded(dlprule.FieldMetadata)
	return u
}

// ClearMetadata clears the value of the "metadata" field.
func (u *DLPRuleUpsert) ClearMetadata() *DLPRuleUpsert {
	u.SetNull(dlprule.FieldMetadata)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *DLPRuleUpsert) SetCreatedBy(v int64) *DLPRuleUpsert {
	u.Set(dlprule.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *DLPRuleUpsert) UpdateCreatedBy() *DLPRuleUpsert {
	u.SetExcluded(dlprule.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *DLPRuleUpsert) AddCreatedBy(v int64) *DLPRuleUpsert {
	u.Add(dlprule.FieldCreatedBy, v)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *DLPRuleUpsert) ClearCreatedBy() *DLPRuleUpsert {
	u.SetNull(dlprule.FieldCreatedBy)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DLPRuleUpsert) SetUpdatedAt(v time.Time) *DLPRuleUpsert {
	u.Set(dlprule.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DLPRuleUpsert) UpdateUpdatedAt() *DLPRuleUpsert {
	u.SetExcluded(dlprule.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.DLPRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DLPRuleUpsertOne) UpdateNewValues() *DLPRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(dlprule.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DLPRule.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DLPRuleUpsertOne) Ignore() *DLPRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DLPRuleUpsertOne) DoNothing() *DLPRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DLPRuleCreate.OnConflict
// documentation for more info.
func (u *DLPRuleUpsertOne) Update(set func(*DLPRuleUpsert)) *DLPRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DLPRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *DLPRuleUpsertOne) SetName(v string) *DLPRuleUpsertOne {
	return u.Update(func(s *DLPRuleUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *DLPRuleUpsertOne) UpdateName() *DLPRuleUpsertOne {
	return u.Update(func(s *DLPRuleUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *DLPRuleUpsertOne) SetDescription(v string) *DLPRuleUpsertOne {
	return u.Update(func(s *DLPRuleUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *DLPRuleUpsertOne) UpdateDescription() *DLPRuleUpsertOne {
	return u.Update(func(s *DLPRuleUpsert) {
		s.UpdateDescription()
	})
}

// SetCategory sets the "category" field.
func (u *DLPRuleUpsertOne) SetCategory(v string) *DLPRuleUpsertOne {
	return u.Update(func(s *DLPRuleUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *DLPRuleUpsertOne) UpdateCategory() *DLPRuleUpsertOne {
	return u.Update(func(s *DLPRuleUpsert) {
		s.UpdateCategory()
	})
}

// SetPattern sets the "pattern" field.
func (u *DLPRuleUpsertOne) SetPattern(v string) *DLPRuleUpsertOne {
	return u.Update(func(s *DLPRuleUpsert) {
		s.SetPattern(v)
	})
}

// UpdatePattern sets the "pattern" field to the value that was provided on create.
func (u *DLPRuleUpsertOne) UpdatePattern() *DLPRuleUpsertOne {
	return u.Update(func(s *DLPRuleUpsert) {
		s.UpdatePattern()
	})
}

// SetPatternType sets the "pattern_type" field.
func (u *DLPRuleUpsertOne) SetPatternType(v string) *DLPRuleUpsertOne {
	return u.Update(func(s *DLPRuleUpsert) {
		s.SetPatternType(v)
	})
}

// UpdatePatternType sets the "pattern_type" field to the value that was provided on create.
func (u *DLPRuleUpsertOne) UpdatePatternType() *DLPRuleUpsertOne {
	return u.Update(func(s *DLPRuleUpsert) {
		s.UpdatePatternType()
	})
}

// SetSeverity sets the "severity" field.
func (u *DLPRuleUpsertOne) SetSeverity(v string) *DLPRuleUpsertOne {
	return u.Update(func(s *DLPRuleUpsert) {
		s.SetSeverity(v)
	})
}

// UpdateSeverity sets the "severity" field to the value that was provided on create.
func (u *DLPRuleUpsertOne) UpdateSeverity() *DLPRuleUpsertOne {
	return u.Update(func(s *DLPRuleUpsert) {
		s.UpdateSeverity()
	})
}

// SetAction sets the "action" field.
func (u *DLPRuleUpsertOne) SetAction(v string) *DLPRuleUpsertOne {
	return u.Update(func(s *DLPRuleUpsert) {
		s.SetAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *DLPRuleUpsertOne) UpdateAction() *DLPRuleUpsertOne {
	return u.Update(func(s *DLPRuleUpsert) {
		s.UpdateAction()
	})
}

// SetMaskContent sets the "mask_content" field.
func (u *DLPRuleUpsertOne) SetMaskContent(v bool) *DLPRuleUpsertOne {
	return u.Update(func(s *DLPRuleUpsert) {
		s.SetMaskContent(v)
	})
}

// UpdateMaskContent sets the "mask_content" field to the value that was provided on create.
func (u *DLPRuleUpsertOne) UpdateMaskContent() *DLPRuleUpsertOne {
	return u.Update(func(s *DLPRuleUpsert) {
		s.UpdateMaskContent()
	})
}

// SetEnabled sets the "enabled" field.
func (u *DLPRuleUpsertOne) SetEnabled(v bool) *DLPRuleUpsertOne {
	return u.Update(func(s *DLPRuleUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *DLPRuleUpsertOne) UpdateEnabled() *DLPRuleUpsertOne {
	return u.Update(func(s *DLPRuleUpsert) {
		s.UpdateEnabled()
	})
}

// SetPriority sets the "priority" field.
func (u *DLPRuleUpsertOne) SetPriority(v int) *DLPRuleUpsertOne {
	return u.Update(func(s *DLPRuleUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *DLPRuleUpsertOne) AddPriority(v int) *DLPRuleUpsertOne {
	return u.Update(func(s *DLPRuleUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *DLPRuleUpsertOne) UpdatePriority() *DLPRuleUpsertOne {
	return u.Update(func(s *DLPRuleUpsert) {
		s.UpdatePriority()
	})
}

// SetScope sets the "scope" field.
func (u *DLPRuleUpsertOne) SetScope(v string) *DLPRuleUpsertOne {
	return u.Update(func(s *DLPRuleUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *DLPRuleUpsertOne) UpdateScope() *DLPRuleUpsertOne {
	return u.Update(func(s *DLPRuleUpsert) {
		s.UpdateScope()
	})
}

// SetModels sets the "models" field.
func (u *DLPRuleUpsertOne) SetModels(v string) *DLPRuleUpsertOne {
	return u.Update(func(s *DLPRuleUpsert) {
		s.SetModels(v)
	})
}

// UpdateModels sets the "models" field to the value that was provided on create.
func (u *DLPRuleUpsertOne) UpdateModels() *DLPRuleUpsertOne {
	return u.Update(func(s *DLPRuleUpsert) {
		s.UpdateModels()
	})
}

// ClearModels clears the value of the "models" field.
func (u *DLPRuleUpsertOne) ClearModels() *DLPRuleUpsertOne {
	return u.Update(func(s *DLPRuleUpsert) {
		s.ClearModels()
	})
}

// SetMetadata sets the "metadata" field.
func (u *DLPRuleUpsertOne) SetMetadata(v string) *DLPRuleUpsertOne {
	return u.Update(func(s *DLPRuleUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *DLPRuleUpsertOne) UpdateMetadata() *DLPRuleUpsertOne {
	return u.Update(func(s *DLPRuleUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *DLPRuleUpsertOne) ClearMetadata() *DLPRuleUpsertOne {
	return u.Update(func(s *DLPRuleUpsert) {
		s.ClearMetadata()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *DLPRuleUpsertOne) SetCreatedBy(v int64) *DLPRuleUpsertOne {
	return u.Update(func(s *DLPRuleUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *DLPRuleUpsertOne) AddCreatedBy(v int64) *DLPRuleUpsertOne {
	return u.Update(func(s *DLPRuleUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *DLPRuleUpsertOne) UpdateCreatedBy() *DLPRuleUpsertOne {
	return u.Update(func(s *DLPRuleUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *DLPRuleUpsertOne) ClearCreatedBy() *DLPRuleUpsertOne {
	return u.Update(func(s *DLPRuleUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DLPRuleUpsertOne) SetUpdatedAt(v time.Time) *DLPRuleUpsertOne {
	return u.Update(func(s *DLPRuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DLPRuleUpsertOne) UpdateUpdatedAt() *DLPRuleUpsertOne {
	return u.Update(func(s *DLPRuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *DLPRuleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DLPRuleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DLPRuleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DLPRuleUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DLPRuleUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DLPRuleCreateBulk is the builder for creating many DLPRule entities in bulk.
type DLPRuleCreateBulk struct {
	config
	err      error
	builders []*DLPRuleCreate
	conflict []sql.ConflictOption
}

// Save creates the DLPRule entities in the database.
func (_c *DLPRuleCreateBulk) Save(ctx context.Context) ([]*DLPRule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DLPRule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DLPRuleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DLPRuleCreateBulk) SaveX(ctx context.Context) []*DLPRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DLPRuleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DLPRuleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DLPRule.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DLPRuleUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *DLPRuleCreateBulk) OnConflict(opts ...sql.ConflictOption) *DLPRuleUpsertBulk {
	_c.conflict = opts
	return &DLPRuleUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DLPRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DLPRuleCreateBulk) OnConflictColumns(columns ...string) *DLPRuleUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DLPRuleUpsertBulk{
		create: _c,
	}
}

// DLPRuleUpsertBulk is the builder for "upsert"-ing
// a bulk of DLPRule nodes.
type DLPRuleUpsertBulk struct {
	create *DLPRuleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DLPRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DLPRuleUpsertBulk) UpdateNewValues() *DLPRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(dlprule.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DLPRule.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DLPRuleUpsertBulk) Ignore() *DLPRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DLPRuleUpsertBulk) DoNothing() *DLPRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DLPRuleCreateBulk.OnConflict
// documentation for more info.
func (u *DLPRuleUpsertBulk) Update(set func(*DLPRuleUpsert)) *DLPRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DLPRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *DLPRuleUpsertBulk) SetName(v string) *DLPRuleUpsertBulk {
	return u.Update(func(s *DLPRuleUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *DLPRuleUpsertBulk) UpdateName() *DLPRuleUpsertBulk {
	return u.Update(func(s *DLPRuleUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *DLPRuleUpsertBulk) SetDescription(v string) *DLPRuleUpsertBulk {
	return u.Update(func(s *DLPRuleUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *DLPRuleUpsertBulk) UpdateDescription() *DLPRuleUpsertBulk {
	return u.Update(func(s *DLPRuleUpsert) {
		s.UpdateDescription()
	})
}

// SetCategory sets the "category" field.
func (u *DLPRuleUpsertBulk) SetCategory(v string) *DLPRuleUpsertBulk {
	return u.Update(func(s *DLPRuleUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *DLPRuleUpsertBulk) UpdateCategory() *DLPRuleUpsertBulk {
	return u.Update(func(s *DLPRuleUpsert) {
		s.UpdateCategory()
	})
}

// SetPattern sets the "pattern" field.
func (u *DLPRuleUpsertBulk) SetPattern(v string) *DLPRuleUpsertBulk {
	return u.Update(func(s *DLPRuleUpsert) {
		s.SetPattern(v)
	})
}

// UpdatePattern sets the "pattern" field to the value that was provided on create.
func (u *DLPRuleUpsertBulk) UpdatePattern() *DLPRuleUpsertBulk {
	return u.Update(func(s *DLPRuleUpsert) {
		s.UpdatePattern()
	})
}

// SetPatternType sets the "pattern_type" field.
func (u *DLPRuleUpsertBulk) SetPatternType(v string) *DLPRuleUpsertBulk {
	return u.Update(func(s *DLPRuleUpsert) {
		s.SetPatternType(v)
	})
}

// UpdatePatternType sets the "pattern_type" field to the value that was provided on create.
func (u *DLPRuleUpsertBulk) UpdatePatternType() *DLPRuleUpsertBulk {
	return u.Update(func(s *DLPRuleUpsert) {
		s.UpdatePatternType()
	})
}

// SetSeverity sets the "severity" field.
func (u *DLPRuleUpsertBulk) SetSeverity(v string) *DLPRuleUpsertBulk {
	return u.Update(func(s *DLPRuleUpsert) {
		s.SetSeverity(v)
	})
}

// UpdateSeverity sets the "severity" field to the value that was provided on create.
func (u *DLPRuleUpsertBulk) UpdateSeverity() *DLPRuleUpsertBulk {
	return u.Update(func(s *DLPRuleUpsert) {
		s.UpdateSeverity()
	})
}

// SetAction sets the "action" field.
func (u *DLPRuleUpsertBulk) SetAction(v string) *DLPRuleUpsertBulk {
	return u.Update(func(s *DLPRuleUpsert) {
		s.SetAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *DLPRuleUpsertBulk) UpdateAction() *DLPRuleUpsertBulk {
	return u.Update(func(s *DLPRuleUpsert) {
		s.UpdateAction()
	})
}

// SetMaskContent sets the "mask_content" field.
func (u *DLPRuleUpsertBulk) SetMaskContent(v bool) *DLPRuleUpsertBulk {
	return u.Update(func(s *DLPRuleUpsert) {
		s.SetMaskContent(v)
	})
}

// UpdateMaskContent sets the "mask_content" field to the value that was provided on create.
func (u *DLPRuleUpsertBulk) UpdateMaskContent() *DLPRuleUpsertBulk {
	return u.Update(func(s *DLPRuleUpsert) {
		s.UpdateMaskContent()
	})
}

// SetEnabled sets the "enabled" field.
func (u *DLPRuleUpsertBulk) SetEnabled(v bool) *DLPRuleUpsertBulk {
	return u.Update(func(s *DLPRuleUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *DLPRuleUpsertBulk) UpdateEnabled() *DLPRuleUpsertBulk {
	return u.Update(func(s *DLPRuleUpsert) {
		s.UpdateEnabled()
	})
}

// SetPriority sets the "priority" field.
func (u *DLPRuleUpsertBulk) SetPriority(v int) *DLPRuleUpsertBulk {
	return u.Update(func(s *DLPRuleUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *DLPRuleUpsertBulk) AddPriority(v int) *DLPRuleUpsertBulk {
	return u.Update(func(s *DLPRuleUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *DLPRuleUpsertBulk) UpdatePriority() *DLPRuleUpsertBulk {
	return u.Update(func(s *DLPRuleUpsert) {
		s.UpdatePriority()
	})
}

// SetScope sets the "scope" field.
func (u *DLPRuleUpsertBulk) SetScope(v string) *DLPRuleUpsertBulk {
	return u.Update(func(s *DLPRuleUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *DLPRuleUpsertBulk) UpdateScope() *DLPRuleUpsertBulk {
	return u.Update(func(s *DLPRuleUpsert) {
		s.UpdateScope()
	})
}

// SetModels sets the "models" field.
func (u *DLPRuleUpsertBulk) SetModels(v string) *DLPRuleUpsertBulk {
	return u.Update(func(s *DLPRuleUpsert) {
		s.SetModels(v)
	})
}

// UpdateModels sets the "models" field to the value that was provided on create.
func (u *DLPRuleUpsertBulk) UpdateModels() *DLPRuleUpsertBulk {
	return u.Update(func(s *DLPRuleUpsert) {
		s.UpdateModels()
	})
}

// ClearModels clears the value of the "models" field.
func (u *DLPRuleUpsertBulk) ClearModels() *DLPRuleUpsertBulk {
	return u.Update(func(s *DLPRuleUpsert) {
		s.ClearModels()
	})
}

// SetMetadata sets the "metadata" field.
func (u *DLPRuleUpsertBulk) SetMetadata(v string) *DLPRuleUpsertBulk {
	return u.Update(func(s *DLPRuleUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *DLPRuleUpsertBulk) UpdateMetadata() *DLPRuleUpsertBulk {
	return u.Update(func(s *DLPRuleUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *DLPRuleUpsertBulk) ClearMetadata() *DLPRuleUpsertBulk {
	return u.Update(func(s *DLPRuleUpsert) {
		s.ClearMetadata()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *DLPRuleUpsertBulk) SetCreatedBy(v int64) *DLPRuleUpsertBulk {
	return u.Update(func(s *DLPRuleUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *DLPRuleUpsertBulk) AddCreatedBy(v int64) *DLPRuleUpsertBulk {
	return u.Update(func(s *DLPRuleUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *DLPRuleUpsertBulk) UpdateCreatedBy() *DLPRuleUpsertBulk {
	return u.Update(func(s *DLPRuleUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *DLPRuleUpsertBulk) ClearCreatedBy() *DLPRuleUpsertBulk {
	return u.Update(func(s *DLPRuleUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DLPRuleUpsertBulk) SetUpdatedAt(v time.Time) *DLPRuleUpsertBulk {
	return u.Update(func(s *DLPRuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DLPRuleUpsertBulk) UpdateUpdatedAt() *DLPRuleUpsertBulk {
	return u.Update(func(s *DLPRuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *DLPRuleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DLPRuleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DLPRuleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DLPRuleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
