// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/dlprule"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// DLPRuleUpdate is the builder for updating DLPRule entities.
type DLPRuleUpdate struct {
	config
	hooks    []Hook
	mutation *DLPRuleMutation
}

// Where appends a list predicates to the DLPRuleUpdate builder.
func (_u *DLPRuleUpdate) Where(ps ...predicate.DLPRule) *DLPRuleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *DLPRuleUpdate) SetName(v string) *DLPRuleUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DLPRuleUpdate) SetNillableName(v *string) *DLPRuleUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *DLPRuleUpdate) SetDescription(v string) *DLPRuleUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *DLPRuleUpdate) SetNillableDescription(v *string) *DLPRuleUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *DLPRuleUpdate) SetCategory(v string) *DLPRuleUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *DLPRuleUpdate) SetNillableCategory(v *string) *DLPRuleUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetPattern sets the "pattern" field.
func (_u *DLPRuleUpdate) SetPattern(v string) *DLPRuleUpdate {
	_u.mutation.SetPattern(v)
	return _u
}

// SetNillablePattern sets the "pattern" field if the given value is not nil.
func (_u *DLPRuleUpdate) SetNillablePattern(v *string) *DLPRuleUpdate {
	if v != nil {
		_u.SetPattern(*v)
	}
	return _u
}

// SetPatternType sets the "pattern_type" field.
func (_u *DLPRuleUpdate) SetPatternType(v string) *DLPRuleUpdate {
	_u.mutation.SetPatternType(v)
	return _u
}

// SetNillablePatternType sets the "pattern_type" field if the given value is not nil.
func (_u *DLPRuleUpdate) SetNillablePatternType(v *string) *DLPRuleUpdate {
	if v != nil {
		_u.SetPatternType(*v)
	}
	return _u
}

// SetSeverity sets the "severity" field.
func (_u *DLPRuleUpdate) SetSeverity(v string) *DLPRuleUpdate {
	_u.mutation.SetSeverity(v)
	return _u
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (_u *DLPRuleUpdate) SetNillableSeverity(v *string) *DLPRuleUpdate {
	if v != nil {
		_u.SetSeverity(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *DLPRuleUpdate) SetAction(v string) *DLPRuleUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *DLPRuleUpdate) SetNillableAction(v *string) *DLPRuleUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetMaskContent sets the "mask_content" field.
func (_u *DLPRuleUpdate) SetMaskContent(v bool) *DLPRuleUpdate {
	_u.mutation.SetMaskContent(v)
	return _u
}

// SetNillableMaskContent sets the "mask_content" field if the given value is not nil.
func (_u *DLPRuleUpdate) SetNillableMaskContent(v *bool) *DLPRuleUpdate {
	if v != nil {
		_u.SetMaskContent(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *DLPRuleUpdate) SetEnabled(v bool) *DLPRuleUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *DLPRuleUpdate) SetNillableEnabled(v *bool) *DLPRuleUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *DLPRuleUpdate) SetPriority(v int) *DLPRuleUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *DLPRuleUpdate) SetNillablePriority(v *int) *DLPRuleUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *DLPRuleUpdate) AddPriority(v int) *DLPRuleUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetScope sets the "scope" field.
func (_u *DLPRuleUpdate) SetScope(v string) *DLPRuleUpdate {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *DLPRuleUpdate) SetNillableScope(v *string) *DLPRuleUpdate {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetModels sets the "models" field.
func (_u *DLPRuleUpdate) SetModels(v string) *DLPRuleUpdate {
	_u.mutation.SetModels(v)
	return _u
}

// SetNillableModels sets the "models" field if the given value is not nil.
func (_u *DLPRuleUpdate) SetNillableModels(v *string) *DLPRuleUpdate {
	if v != nil {
		_u.SetModels(*v)
	}
	return _u
}

// ClearModels clears the value of the "models" field.
func (_u *DLPRuleUpdate) ClearModels() *DLPRuleUpdate {
	_u.mutation.ClearModels()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *DLPRuleUpdate) SetMetadata(v string) *DLPRuleUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetNillableMetadata sets the "metadata" field if the given value is not nil.
func (_u *DLPRuleUpdate) SetNillableMetadata(v *string) *DLPRuleUpdate {
	if v != nil {
		_u.SetMetadata(*v)
	}
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *DLPRuleUpdate) ClearMetadata() *DLPRuleUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *DLPRuleUpdate) SetCreatedBy(v int64) *DLPRuleUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *DLPRuleUpdate) SetNillableCreatedBy(v *int64) *DLPRuleUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *DLPRuleUpdate) AddCreatedBy(v int64) *DLPRuleUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *DLPRuleUpdate) ClearCreatedBy() *DLPRuleUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DLPRuleUpdate) SetUpdatedAt(v time.Time) *DLPRuleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *DLPRuleUpdate) SetNillableUpdatedAt(v *time.Time) *DLPRuleUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the DLPRuleMutation object of the builder.
func (_u *DLPRuleUpdate) Mutation() *DLPRuleMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DLPRuleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DLPRuleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DLPRuleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DLPRuleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DLPRuleUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := dlprule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DLPRule.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := dlprule.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "DLPRule.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Pattern(); ok {
		if err := dlprule.PatternValidator(v); err != nil {
			return &ValidationError{Name: "pattern", err: fmt.Errorf(`ent: validator failed for field "DLPRule.pattern": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PatternType(); ok {
		if err := dlprule.PatternTypeValidator(v); err != nil {
			return &ValidationError{Name: "pattern_type", err: fmt.Errorf(`ent: validator failed for field "DLPRule.pattern_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Severity(); ok {
		if err := dlprule.SeverityValidator(v); err != nil {
			return &ValidationError{Name: "severity", err: fmt.Errorf(`ent: validator failed for field "DLPRule.severity": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Action(); ok {
		if err := dlprule.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "DLPRule.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Scope(); ok {
		if err := dlprule.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "DLPRule.scope": %w`, err)}
		}
	}
	return nil
}

func (_u *DLPRuleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dlprule.Table, dlprule.Columns, sqlgraph.NewFieldSpec(dlprule.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(dlprule.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(dlprule.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(dlprule.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Pattern(); ok {
		_spec.SetField(dlprule.FieldPattern, field.TypeString, value)
	}
	if value, ok := _u.mutation.PatternType(); ok {
		_spec.SetField(dlprule.FieldPatternType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Severity(); ok {
		_spec.SetField(dlprule.FieldSeverity, field.TypeString, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(dlprule.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.MaskContent(); ok {
		_spec.SetField(dlprule.FieldMaskContent, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(dlprule.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(dlprule.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(dlprule.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(dlprule.FieldScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.Models(); ok {
		_spec.SetField(dlprule.FieldModels, field.TypeString, value)
	}
	if _u.mutation.ModelsCleared() {
		_spec.ClearField(dlprule.FieldModels, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(dlprule.FieldMetadata, field.TypeString, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(dlprule.FieldMetadata, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(dlprule.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(dlprule.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(dlprule.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dlprule.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dlprule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DLPRuleUpdateOne is the builder for updating a single DLPRule entity.
type DLPRuleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DLPRuleMutation
}

// SetName sets the "name" field.
func (_u *DLPRuleUpdateOne) SetName(v string) *DLPRuleUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DLPRuleUpdateOne) SetNillableName(v *string) *DLPRuleUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *DLPRuleUpdateOne) SetDescription(v string) *DLPRuleUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *DLPRuleUpdateOne) SetNillableDescription(v *string) *DLPRuleUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *DLPRuleUpdateOne) SetCategory(v string) *DLPRuleUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *DLPRuleUpdateOne) SetNillableCategory(v *string) *DLPRuleUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetPattern sets the "pattern" field.
func (_u *DLPRuleUpdateOne) SetPattern(v string) *DLPRuleUpdateOne {
	_u.mutation.SetPattern(v)
	return _u
}

// SetNillablePattern sets the "pattern" field if the given value is not nil.
func (_u *DLPRuleUpdateOne) SetNillablePattern(v *string) *DLPRuleUpdateOne {
	if v != nil {
		_u.SetPattern(*v)
	}
	return _u
}

// SetPatternType sets the "pattern_type" field.
func (_u *DLPRuleUpdateOne) SetPatternType(v string) *DLPRuleUpdateOne {
	_u.mutation.SetPatternType(v)
	return _u
}

// SetNillablePatternType sets the "pattern_type" field if the given value is not nil.
func (_u *DLPRuleUpdateOne) SetNillablePatternType(v *string) *DLPRuleUpdateOne {
	if v != nil {
		_u.SetPatternType(*v)
	}
	return _u
}

// SetSeverity sets the "severity" field.
func (_u *DLPRuleUpdateOne) SetSeverity(v string) *DLPRuleUpdateOne {
	_u.mutation.SetSeverity(v)
	return _u
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (_u *DLPRuleUpdateOne) SetNillableSeverity(v *string) *DLPRuleUpdateOne {
	if v != nil {
		_u.SetSeverity(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *DLPRuleUpdateOne) SetAction(v string) *DLPRuleUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *DLPRuleUpdateOne) SetNillableAction(v *string) *DLPRuleUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetMaskContent sets the "mask_content" field.
func (_u *DLPRuleUpdateOne) SetMaskContent(v bool) *DLPRuleUpdateOne {
	_u.mutation.SetMaskContent(v)
	return _u
}

// SetNillableMaskContent sets the "mask_content" field if the given value is not nil.
func (_u *DLPRuleUpdateOne) SetNillableMaskContent(v *bool) *DLPRuleUpdateOne {
	if v != nil {
		_u.SetMaskContent(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *DLPRuleUpdateOne) SetEnabled(v bool) *DLPRuleUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *DLPRuleUpdateOne) SetNillableEnabled(v *bool) *DLPRuleUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *DLPRuleUpdateOne) SetPriority(v int) *DLPRuleUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *DLPRuleUpdateOne) SetNillablePriority(v *int) *DLPRuleUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *DLPRuleUpdateOne) AddPriority(v int) *DLPRuleUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetScope sets the "scope" field.
func (_u *DLPRuleUpdateOne) SetScope(v string) *DLPRuleUpdateOne {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *DLPRuleUpdateOne) SetNillableScope(v *string) *DLPRuleUpdateOne {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetModels sets the "models" field.
func (_u *DLPRuleUpdateOne) SetModels(v string) *DLPRuleUpdateOne {
	_u.mutation.SetModels(v)
	return _u
}

// SetNillableModels sets the "models" field if the given value is not nil.
func (_u *DLPRuleUpdateOne) SetNillableModels(v *string) *DLPRuleUpdateOne {
	if v != nil {
		_u.SetModels(*v)
	}
	return _u
}

// ClearModels clears the value of the "models" field.
func (_u *DLPRuleUpdateOne) ClearModels() *DLPRuleUpdateOne {
	_u.mutation.ClearModels()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *DLPRuleUpdateOne) SetMetadata(v string) *DLPRuleUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetNillableMetadata sets the "metadata" field if the given value is not nil.
func (_u *DLPRuleUpdateOne) SetNillableMetadata(v *string) *DLPRuleUpdateOne {
	if v != nil {
		_u.SetMetadata(*v)
	}
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *DLPRuleUpdateOne) ClearMetadata() *DLPRuleUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *DLPRuleUpdateOne) SetCreatedBy(v int64) *DLPRuleUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *DLPRuleUpdateOne) SetNillableCreatedBy(v *int64) *DLPRuleUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *DLPRuleUpdateOne) AddCreatedBy(v int64) *DLPRuleUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *DLPRuleUpdateOne) ClearCreatedBy() *DLPRuleUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DLPRuleUpdateOne) SetUpdatedAt(v time.Time) *DLPRuleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *DLPRuleUpdateOne) SetNillableUpdatedAt(v *time.Time) *DLPRuleUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the DLPRuleMutation object of the builder.
func (_u *DLPRuleUpdateOne) Mutation() *DLPRuleMutation {
	return _u.mutation
}

// Where appends a list predicates to the DLPRuleUpdate builder.
func (_u *DLPRuleUpdateOne) Where(ps ...predicate.DLPRule) *DLPRuleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DLPRuleUpdateOne) Select(field string, fields ...string) *DLPRuleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DLPRule entity.
func (_u *DLPRuleUpdateOne) Save(ctx context.Context) (*DLPRule, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DLPRuleUpdateOne) SaveX(ctx context.Context) *DLPRule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DLPRuleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DLPRuleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DLPRuleUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := dlprule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DLPRule.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := dlprule.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "DLPRule.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Pattern(); ok {
		if err := dlprule.PatternValidator(v); err != nil {
			return &ValidationError{Name: "pattern", err: fmt.Errorf(`ent: validator failed for field "DLPRule.pattern": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PatternType(); ok {
		if err := dlprule.PatternTypeValidator(v); err != nil {
			return &ValidationError{Name: "pattern_type", err: fmt.Errorf(`ent: validator failed for field "DLPRule.pattern_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Severity(); ok {
		if err := dlprule.SeverityValidator(v); err != nil {
			return &ValidationError{Name: "severity", err: fmt.Errorf(`ent: validator failed for field "DLPRule.severity": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Action(); ok {
		if err := dlprule.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "DLPRule.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Scope(); ok {
		if err := dlprule.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "DLPRule.scope": %w`, err)}
		}
	}
	return nil
}

func (_u *DLPRuleUpdateOne) sqlSave(ctx context.Context) (_node *DLPRule, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dlprule.Table, dlprule.Columns, sqlgraph.NewFieldSpec(dlprule.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DLPRule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dlprule.FieldID)
		for _, f := range fields {
			if !dlprule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dlprule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(dlprule.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(dlprule.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(dlprule.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Pattern(); ok {
		_spec.SetField(dlprule.FieldPattern, field.TypeString, value)
	}
	if value, ok := _u.mutation.PatternType(); ok {
		_spec.SetField(dlprule.FieldPatternType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Severity(); ok {
		_spec.SetField(dlprule.FieldSeverity, field.TypeString, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(dlprule.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.MaskContent(); ok {
		_spec.SetField(dlprule.FieldMaskContent, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(dlprule.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(dlprule.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(dlprule.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(dlprule.FieldScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.Models(); ok {
		_spec.SetField(dlprule.FieldModels, field.TypeString, value)
	}
	if _u.mutation.ModelsCleared() {
		_spec.ClearField(dlprule.FieldModels, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(dlprule.FieldMetadata, field.TypeString, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(dlprule.FieldMetadata, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(dlprule.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(dlprule.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(dlprule.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dlprule.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &DLPRule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dlprule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
