// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/securityevent"
)

// SecurityEventUpdate is the builder for updating SecurityEvent entities.
type SecurityEventUpdate struct {
	config
	hooks    []Hook
	mutation *SecurityEventMutation
}

// Where appends a list predicates to the SecurityEventUpdate builder.
func (_u *SecurityEventUpdate) Where(ps ...predicate.SecurityEvent) *SecurityEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *SecurityEventUpdate) SetEventType(v string) *SecurityEventUpdate {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *SecurityEventUpdate) SetNillableEventType(v *string) *SecurityEventUpdate {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetSeverity sets the "severity" field.
func (_u *SecurityEventUpdate) SetSeverity(v string) *SecurityEventUpdate {
	_u.mutation.SetSeverity(v)
	return _u
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (_u *SecurityEventUpdate) SetNillableSeverity(v *string) *SecurityEventUpdate {
	if v != nil {
		_u.SetSeverity(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *SecurityEventUpdate) SetCategory(v string) *SecurityEventUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *SecurityEventUpdate) SetNillableCategory(v *string) *SecurityEventUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *SecurityEventUpdate) SetTitle(v string) *SecurityEventUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *SecurityEventUpdate) SetNillableTitle(v *string) *SecurityEventUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *SecurityEventUpdate) SetDescription(v string) *SecurityEventUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SecurityEventUpdate) SetNillableDescription(v *string) *SecurityEventUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SecurityEventUpdate) SetUserID(v int64) *SecurityEventUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SecurityEventUpdate) SetNillableUserID(v *int64) *SecurityEventUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *SecurityEventUpdate) AddUserID(v int64) *SecurityEventUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *SecurityEventUpdate) ClearUserID() *SecurityEventUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *SecurityEventUpdate) SetAPIKeyID(v int64) *SecurityEventUpdate {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *SecurityEventUpdate) SetNillableAPIKeyID(v *int64) *SecurityEventUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *SecurityEventUpdate) AddAPIKeyID(v int64) *SecurityEventUpdate {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (_u *SecurityEventUpdate) ClearAPIKeyID() *SecurityEventUpdate {
	_u.mutation.ClearAPIKeyID()
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *SecurityEventUpdate) SetRequestID(v string) *SecurityEventUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *SecurityEventUpdate) SetNillableRequestID(v *string) *SecurityEventUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *SecurityEventUpdate) ClearRequestID() *SecurityEventUpdate {
	_u.mutation.ClearRequestID()
	return _u
}

// SetModel sets the "model" field.
func (_u *SecurityEventUpdate) SetModel(v string) *SecurityEventUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *SecurityEventUpdate) SetNillableModel(v *string) *SecurityEventUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// ClearModel clears the value of the "model" field.
func (_u *SecurityEventUpdate) ClearModel() *SecurityEventUpdate {
	_u.mutation.ClearModel()
	return _u
}

// SetAction sets the "action" field.
func (_u *SecurityEventUpdate) SetAction(v string) *SecurityEventUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *SecurityEventUpdate) SetNillableAction(v *string) *SecurityEventUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetMatchedPatterns sets the "matched_patterns" field.
func (_u *SecurityEventUpdate) SetMatchedPatterns(v string) *SecurityEventUpdate {
	_u.mutation.SetMatchedPatterns(v)
	return _u
}

// SetNillableMatchedPatterns sets the "matched_patterns" field if the given value is not nil.
func (_u *SecurityEventUpdate) SetNillableMatchedPatterns(v *string) *SecurityEventUpdate {
	if v != nil {
		_u.SetMatchedPatterns(*v)
	}
	return _u
}

// ClearMatchedPatterns clears the value of the "matched_patterns" field.
func (_u *SecurityEventUpdate) ClearMatchedPatterns() *SecurityEventUpdate {
	_u.mutation.ClearMatchedPatterns()
	return _u
}

// SetConfidence sets the "confidence" field.
func (_u *SecurityEventUpdate) SetConfidence(v float64) *SecurityEventUpdate {
	_u.mutation.ResetConfidence()
	_u.mutation.SetConfidence(v)
	return _u
}

// SetNillableConfidence sets the "confidence" field if the given value is not nil.
func (_u *SecurityEventUpdate) SetNillableConfidence(v *float64) *SecurityEventUpdate {
	if v != nil {
		_u.SetConfidence(*v)
	}
	return _u
}

// AddConfidence adds value to the "confidence" field.
func (_u *SecurityEventUpdate) AddConfidence(v float64) *SecurityEventUpdate {
	_u.mutation.AddConfidence(v)
	return _u
}

// SetRequestSnapshot sets the "request_snapshot" field.
func (_u *SecurityEventUpdate) SetRequestSnapshot(v string) *SecurityEventUpdate {
	_u.mutation.SetRequestSnapshot(v)
	return _u
}

// SetNillableRequestSnapshot sets the "request_snapshot" field if the given value is not nil.
func (_u *SecurityEventUpdate) SetNillableRequestSnapshot(v *string) *SecurityEventUpdate {
	if v != nil {
		_u.SetRequestSnapshot(*v)
	}
	return _u
}

// ClearRequestSnapshot clears the value of the "request_snapshot" field.
func (_u *SecurityEventUpdate) ClearRequestSnapshot() *SecurityEventUpdate {
	_u.mutation.ClearRequestSnapshot()
	return _u
}

// SetSourceIP sets the "source_ip" field.
func (_u *SecurityEventUpdate) SetSourceIP(v string) *SecurityEventUpdate {
	_u.mutation.SetSourceIP(v)
	return _u
}

// SetNillableSourceIP sets the "source_ip" field if the given value is not nil.
func (_u *SecurityEventUpdate) SetNillableSourceIP(v *string) *SecurityEventUpdate {
	if v != nil {
		_u.SetSourceIP(*v)
	}
	return _u
}

// ClearSourceIP clears the value of the "source_ip" field.
func (_u *SecurityEventUpdate) ClearSourceIP() *SecurityEventUpdate {
	_u.mutation.ClearSourceIP()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *SecurityEventUpdate) SetUserAgent(v string) *SecurityEventUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *SecurityEventUpdate) SetNillableUserAgent(v *string) *SecurityEventUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *SecurityEventUpdate) ClearUserAgent() *SecurityEventUpdate {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetStatus sets the "status" field.
func (_u *SecurityEventUpdate) SetStatus(v string) *SecurityEventUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SecurityEventUpdate) SetNillableStatus(v *string) *SecurityEventUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetResolution sets the "resolution" field.
func (_u *SecurityEventUpdate) SetResolution(v string) *SecurityEventUpdate {
	_u.mutation.SetResolution(v)
	return _u
}

// SetNillableResolution sets the "resolution" field if the given value is not nil.
func (_u *SecurityEventUpdate) SetNillableResolution(v *string) *SecurityEventUpdate {
	if v != nil {
		_u.SetResolution(*v)
	}
	return _u
}

// ClearResolution clears the value of the "resolution" field.
func (_u *SecurityEventUpdate) ClearResolution() *SecurityEventUpdate {
	_u.mutation.ClearResolution()
	return _u
}

// SetResolvedAt sets the "resolved_at" field.
func (_u *SecurityEventUpdate) SetResolvedAt(v time.Time) *SecurityEventUpdate {
	_u.mutation.SetResolvedAt(v)
	return _u
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (_u *SecurityEventUpdate) SetNillableResolvedAt(v *time.Time) *SecurityEventUpdate {
	if v != nil {
		_u.SetResolvedAt(*v)
	}
	return _u
}

// ClearResolvedAt clears the value of the "resolved_at" field.
func (_u *SecurityEventUpdate) ClearResolvedAt() *SecurityEventUpdate {
	_u.mutation.ClearResolvedAt()
	return _u
}

// Mutation returns the SecurityEventMutation object of the builder.
func (_u *SecurityEventUpdate) Mutation() *SecurityEventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SecurityEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SecurityEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SecurityEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SecurityEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SecurityEventUpdate) check() error {
	if v, ok := _u.mutation.EventType(); ok {
		if err := securityevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "SecurityEvent.event_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Severity(); ok {
		if err := securityevent.SeverityValidator(v); err != nil {
			return &ValidationError{Name: "severity", err: fmt.Errorf(`ent: validator failed for field "SecurityEvent.severity": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := securityevent.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "SecurityEvent.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := securityevent.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "SecurityEvent.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := securityevent.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "SecurityEvent.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := securityevent.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "SecurityEvent.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Action(); ok {
		if err := securityevent.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "SecurityEvent.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceIP(); ok {
		if err := securityevent.SourceIPValidator(v); err != nil {
			return &ValidationError{Name: "source_ip", err: fmt.Errorf(`ent: validator failed for field "SecurityEvent.source_ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAgent(); ok {
		if err := securityevent.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "SecurityEvent.user_agent": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := securityevent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SecurityEvent.status": %w`, err)}
		}
	}
	return nil
}

func (_u *SecurityEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(securityevent.Table, securityevent.Columns, sqlgraph.NewFieldSpec(securityevent.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(securityevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Severity(); ok {
		_spec.SetField(securityevent.FieldSeverity, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(securityevent.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(securityevent.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(securityevent.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(securityevent.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(securityevent.FieldUserID, field.TypeInt64, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(securityevent.FieldUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(securityevent.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(securityevent.FieldAPIKeyID, field.TypeInt64, value)
	}
	if _u.mutation.APIKeyIDCleared() {
		_spec.ClearField(securityevent.FieldAPIKeyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(securityevent.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(securityevent.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(securityevent.FieldModel, field.TypeString, value)
	}
	if _u.mutation.ModelCleared() {
		_spec.ClearField(securityevent.FieldModel, field.TypeString)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(securityevent.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.MatchedPatterns(); ok {
		_spec.SetField(securityevent.FieldMatchedPatterns, field.TypeString, value)
	}
	if _u.mutation.MatchedPatternsCleared() {
		_spec.ClearField(securityevent.FieldMatchedPatterns, field.TypeString)
	}
	if value, ok := _u.mutation.Confidence(); ok {
		_spec.SetField(securityevent.FieldConfidence, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedConfidence(); ok {
		_spec.AddField(securityevent.FieldConfidence, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RequestSnapshot(); ok {
		_spec.SetField(securityevent.FieldRequestSnapshot, field.TypeString, value)
	}
	if _u.mutation.RequestSnapshotCleared() {
		_spec.ClearField(securityevent.FieldRequestSnapshot, field.TypeString)
	}
	if value, ok := _u.mutation.SourceIP(); ok {
		_spec.SetField(securityevent.FieldSourceIP, field.TypeString, value)
	}
	if _u.mutation.SourceIPCleared() {
		_spec.ClearField(securityevent.FieldSourceIP, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(securityevent.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(securityevent.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(securityevent.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Resolution(); ok {
		_spec.SetField(securityevent.FieldResolution, field.TypeString, value)
	}
	if _u.mutation.ResolutionCleared() {
		_spec.ClearField(securityevent.FieldResolution, field.TypeString)
	}
	if value, ok := _u.mutation.ResolvedAt(); ok {
		_spec.SetField(securityevent.FieldResolvedAt, field.TypeTime, value)
	}
	if _u.mutation.ResolvedAtCleared() {
		_spec.ClearField(securityevent.FieldResolvedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{securityevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SecurityEventUpdateOne is the builder for updating a single SecurityEvent entity.
type SecurityEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SecurityEventMutation
}

// SetEventType sets the "event_type" field.
func (_u *SecurityEventUpdateOne) SetEventType(v string) *SecurityEventUpdateOne {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *SecurityEventUpdateOne) SetNillableEventType(v *string) *SecurityEventUpdateOne {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetSeverity sets the "severity" field.
func (_u *SecurityEventUpdateOne) SetSeverity(v string) *SecurityEventUpdateOne {
	_u.mutation.SetSeverity(v)
	return _u
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (_u *SecurityEventUpdateOne) SetNillableSeverity(v *string) *SecurityEventUpdateOne {
	if v != nil {
		_u.SetSeverity(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *SecurityEventUpdateOne) SetCategory(v string) *SecurityEventUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *SecurityEventUpdateOne) SetNillableCategory(v *string) *SecurityEventUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *SecurityEventUpdateOne) SetTitle(v string) *SecurityEventUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *SecurityEventUpdateOne) SetNillableTitle(v *string) *SecurityEventUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *SecurityEventUpdateOne) SetDescription(v string) *SecurityEventUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SecurityEventUpdateOne) SetNillableDescription(v *string) *SecurityEventUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SecurityEventUpdateOne) SetUserID(v int64) *SecurityEventUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SecurityEventUpdateOne) SetNillableUserID(v *int64) *SecurityEventUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *SecurityEventUpdateOne) AddUserID(v int64) *SecurityEventUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *SecurityEventUpdateOne) ClearUserID() *SecurityEventUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *SecurityEventUpdateOne) SetAPIKeyID(v int64) *SecurityEventUpdateOne {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *SecurityEventUpdateOne) SetNillableAPIKeyID(v *int64) *SecurityEventUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *SecurityEventUpdateOne) AddAPIKeyID(v int64) *SecurityEventUpdateOne {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (_u *SecurityEventUpdateOne) ClearAPIKeyID() *SecurityEventUpdateOne {
	_u.mutation.ClearAPIKeyID()
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *SecurityEventUpdateOne) SetRequestID(v string) *SecurityEventUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *SecurityEventUpdateOne) SetNillableRequestID(v *string) *SecurityEventUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *SecurityEventUpdateOne) ClearRequestID() *SecurityEventUpdateOne {
	_u.mutation.ClearRequestID()
	return _u
}

// SetModel sets the "model" field.
func (_u *SecurityEventUpdateOne) SetModel(v string) *SecurityEventUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *SecurityEventUpdateOne) SetNillableModel(v *string) *SecurityEventUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// ClearModel clears the value of the "model" field.
func (_u *SecurityEventUpdateOne) ClearModel() *SecurityEventUpdateOne {
	_u.mutation.ClearModel()
	return _u
}

// SetAction sets the "action" field.
func (_u *SecurityEventUpdateOne) SetAction(v string) *SecurityEventUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *SecurityEventUpdateOne) SetNillableAction(v *string) *SecurityEventUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetMatchedPatterns sets the "matched_patterns" field.
func (_u *SecurityEventUpdateOne) SetMatchedPatterns(v string) *SecurityEventUpdateOne {
	_u.mutation.SetMatchedPatterns(v)
	return _u
}

// SetNillableMatchedPatterns sets the "matched_patterns" field if the given value is not nil.
func (_u *SecurityEventUpdateOne) SetNillableMatchedPatterns(v *string) *SecurityEventUpdateOne {
	if v != nil {
		_u.SetMatchedPatterns(*v)
	}
	return _u
}

// ClearMatchedPatterns clears the value of the "matched_patterns" field.
func (_u *SecurityEventUpdateOne) ClearMatchedPatterns() *SecurityEventUpdateOne {
	_u.mutation.ClearMatchedPatterns()
	return _u
}

// SetConfidence sets the "confidence" field.
func (_u *SecurityEventUpdateOne) SetConfidence(v float64) *SecurityEventUpdateOne {
	_u.mutation.ResetConfidence()
	_u.mutation.SetConfidence(v)
	return _u
}

// SetNillableConfidence sets the "confidence" field if the given value is not nil.
func (_u *SecurityEventUpdateOne) SetNillableConfidence(v *float64) *SecurityEventUpdateOne {
	if v != nil {
		_u.SetConfidence(*v)
	}
	return _u
}

// AddConfidence adds value to the "confidence" field.
func (_u *SecurityEventUpdateOne) AddConfidence(v float64) *SecurityEventUpdateOne {
	_u.mutation.AddConfidence(v)
	return _u
}

// SetRequestSnapshot sets the "request_snapshot" field.
func (_u *SecurityEventUpdateOne) SetRequestSnapshot(v string) *SecurityEventUpdateOne {
	_u.mutation.SetRequestSnapshot(v)
	return _u
}

// SetNillableRequestSnapshot sets the "request_snapshot" field if the given value is not nil.
func (_u *SecurityEventUpdateOne) SetNillableRequestSnapshot(v *string) *SecurityEventUpdateOne {
	if v != nil {
		_u.SetRequestSnapshot(*v)
	}
	return _u
}

// ClearRequestSnapshot clears the value of the "request_snapshot" field.
func (_u *SecurityEventUpdateOne) ClearRequestSnapshot() *SecurityEventUpdateOne {
	_u.mutation.ClearRequestSnapshot()
	return _u
}

// SetSourceIP sets the "source_ip" field.
func (_u *SecurityEventUpdateOne) SetSourceIP(v string) *SecurityEventUpdateOne {
	_u.mutation.SetSourceIP(v)
	return _u
}

// SetNillableSourceIP sets the "source_ip" field if the given value is not nil.
func (_u *SecurityEventUpdateOne) SetNillableSourceIP(v *string) *SecurityEventUpdateOne {
	if v != nil {
		_u.SetSourceIP(*v)
	}
	return _u
}

// ClearSourceIP clears the value of the "source_ip" field.
func (_u *SecurityEventUpdateOne) ClearSourceIP() *SecurityEventUpdateOne {
	_u.mutation.ClearSourceIP()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *SecurityEventUpdateOne) SetUserAgent(v string) *SecurityEventUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *SecurityEventUpdateOne) SetNillableUserAgent(v *string) *SecurityEventUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *SecurityEventUpdateOne) ClearUserAgent() *SecurityEventUpdateOne {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetStatus sets the "status" field.
func (_u *SecurityEventUpdateOne) SetStatus(v string) *SecurityEventUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SecurityEventUpdateOne) SetNillableStatus(v *string) *SecurityEventUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetResolution sets the "resolution" field.
func (_u *SecurityEventUpdateOne) SetResolution(v string) *SecurityEventUpdateOne {
	_u.mutation.SetResolution(v)
	return _u
}

// SetNillableResolution sets the "resolution" field if the given value is not nil.
func (_u *SecurityEventUpdateOne) SetNillableResolution(v *string) *SecurityEventUpdateOne {
	if v != nil {
		_u.SetResolution(*v)
	}
	return _u
}

// ClearResolution clears the value of the "resolution" field.
func (_u *SecurityEventUpdateOne) ClearResolution() *SecurityEventUpdateOne {
	_u.mutation.ClearResolution()
	return _u
}

// SetResolvedAt sets the "resolved_at" field.
func (_u *SecurityEventUpdateOne) SetResolvedAt(v time.Time) *SecurityEventUpdateOne {
	_u.mutation.SetResolvedAt(v)
	return _u
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (_u *SecurityEventUpdateOne) SetNillableResolvedAt(v *time.Time) *SecurityEventUpdateOne {
	if v != nil {
		_u.SetResolvedAt(*v)
	}
	return _u
}

// ClearResolvedAt clears the value of the "resolved_at" field.
func (_u *SecurityEventUpdateOne) ClearResolvedAt() *SecurityEventUpdateOne {
	_u.mutation.ClearResolvedAt()
	return _u
}

// Mutation returns the SecurityEventMutation object of the builder.
func (_u *SecurityEventUpdateOne) Mutation() *SecurityEventMutation {
	return _u.mutation
}

// Where appends a list predicates to the SecurityEventUpdate builder.
func (_u *SecurityEventUpdateOne) Where(ps ...predicate.SecurityEvent) *SecurityEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SecurityEventUpdateOne) Select(field string, fields ...string) *SecurityEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SecurityEvent entity.
func (_u *SecurityEventUpdateOne) Save(ctx context.Context) (*SecurityEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SecurityEventUpdateOne) SaveX(ctx context.Context) *SecurityEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SecurityEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SecurityEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SecurityEventUpdateOne) check() error {
	if v, ok := _u.mutation.EventType(); ok {
		if err := securityevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "SecurityEvent.event_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Severity(); ok {
		if err := securityevent.SeverityValidator(v); err != nil {
			return &ValidationError{Name: "severity", err: fmt.Errorf(`ent: validator failed for field "SecurityEvent.severity": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := securityevent.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "SecurityEvent.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := securityevent.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "SecurityEvent.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := securityevent.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "SecurityEvent.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := securityevent.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "SecurityEvent.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Action(); ok {
		if err := securityevent.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "SecurityEvent.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceIP(); ok {
		if err := securityevent.SourceIPValidator(v); err != nil {
			return &ValidationError{Name: "source_ip", err: fmt.Errorf(`ent: validator failed for field "SecurityEvent.source_ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAgent(); ok {
		if err := securityevent.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "SecurityEvent.user_agent": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := securityevent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SecurityEvent.status": %w`, err)}
		}
	}
	return nil
}

func (_u *SecurityEventUpdateOne) sqlSave(ctx context.Context) (_node *SecurityEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(securityevent.Table, securityevent.Columns, sqlgraph.NewFieldSpec(securityevent.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SecurityEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, securityevent.FieldID)
		for _, f := range fields {
			if !securityevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != securityevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(securityevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Severity(); ok {
		_spec.SetField(securityevent.FieldSeverity, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(securityevent.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(securityevent.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(securityevent.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(securityevent.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(securityevent.FieldUserID, field.TypeInt64, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(securityevent.FieldUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(securityevent.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(securityevent.FieldAPIKeyID, field.TypeInt64, value)
	}
	if _u.mutation.APIKeyIDCleared() {
		_spec.ClearField(securityevent.FieldAPIKeyID, field.TypeInt64)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(securityevent.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(securityevent.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(securityevent.FieldModel, field.TypeString, value)
	}
	if _u.mutation.ModelCleared() {
		_spec.ClearField(securityevent.FieldModel, field.TypeString)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(securityevent.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.MatchedPatterns(); ok {
		_spec.SetField(securityevent.FieldMatchedPatterns, field.TypeString, value)
	}
	if _u.mutation.MatchedPatternsCleared() {
		_spec.ClearField(securityevent.FieldMatchedPatterns, field.TypeString)
	}
	if value, ok := _u.mutation.Confidence(); ok {
		_spec.SetField(securityevent.FieldConfidence, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedConfidence(); ok {
		_spec.AddField(securityevent.FieldConfidence, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RequestSnapshot(); ok {
		_spec.SetField(securityevent.FieldRequestSnapshot, field.TypeString, value)
	}
	if _u.mutation.RequestSnapshotCleared() {
		_spec.ClearField(securityevent.FieldRequestSnapshot, field.TypeString)
	}
	if value, ok := _u.mutation.SourceIP(); ok {
		_spec.SetField(securityevent.FieldSourceIP, field.TypeString, value)
	}
	if _u.mutation.SourceIPCleared() {
		_spec.ClearField(securityevent.FieldSourceIP, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(securityevent.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(securityevent.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(securityevent.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Resolution(); ok {
		_spec.SetField(securityevent.FieldResolution, field.TypeString, value)
	}
	if _u.mutation.ResolutionCleared() {
		_spec.ClearField(securityevent.FieldResolution, field.TypeString)
	}
	if value, ok := _u.mutation.ResolvedAt(); ok {
		_spec.SetField(securityevent.FieldResolvedAt, field.TypeTime, value)
	}
	if _u.mutation.ResolvedAtCleared() {
		_spec.ClearField(securityevent.FieldResolvedAt, field.TypeTime)
	}
	_node = &SecurityEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{securityevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
