// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/securityevent"
)

// SecurityEventCreate is the builder for creating a SecurityEvent entity.
type SecurityEventCreate struct {
	config
	mutation *SecurityEventMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetEventType sets the "event_type" field.
func (_c *SecurityEventCreate) SetEventType(v string) *SecurityEventCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetSeverity sets the "severity" field.
func (_c *SecurityEventCreate) SetSeverity(v string) *SecurityEventCreate {
	_c.mutation.SetSeverity(v)
	return _c
}

// SetCategory sets the "category" field.
func (_c *SecurityEventCreate) SetCategory(v string) *SecurityEventCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *SecurityEventCreate) SetTitle(v string) *SecurityEventCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *SecurityEventCreate) SetDescription(v string) *SecurityEventCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *SecurityEventCreate) SetUserID(v int64) *SecurityEventCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *SecurityEventCreate) SetNillableUserID(v *int64) *SecurityEventCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *SecurityEventCreate) SetAPIKeyID(v int64) *SecurityEventCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_c *SecurityEventCreate) SetNillableAPIKeyID(v *int64) *SecurityEventCreate {
	if v != nil {
		_c.SetAPIKeyID(*v)
	}
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *SecurityEventCreate) SetRequestID(v string) *SecurityEventCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_c *SecurityEventCreate) SetNillableRequestID(v *string) *SecurityEventCreate {
	if v != nil {
		_c.SetRequestID(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *SecurityEventCreate) SetModel(v string) *SecurityEventCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *SecurityEventCreate) SetNillableModel(v *string) *SecurityEventCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetAction sets the "action" field.
func (_c *SecurityEventCreate) SetAction(v string) *SecurityEventCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_c *SecurityEventCreate) SetNillableAction(v *string) *SecurityEventCreate {
	if v != nil {
		_c.SetAction(*v)
	}
	return _c
}

// SetMatchedPatterns sets the "matched_patterns" field.
func (_c *SecurityEventCreate) SetMatchedPatterns(v string) *SecurityEventCreate {
	_c.mutation.SetMatchedPatterns(v)
	return _c
}

// SetNillableMatchedPatterns sets the "matched_patterns" field if the given value is not nil.
func (_c *SecurityEventCreate) SetNillableMatchedPatterns(v *string) *SecurityEventCreate {
	if v != nil {
		_c.SetMatchedPatterns(*v)
	}
	return _c
}

// SetConfidence sets the "confidence" field.
func (_c *SecurityEventCreate) SetConfidence(v float64) *SecurityEventCreate {
	_c.mutation.SetConfidence(v)
	return _c
}

// SetNillableConfidence sets the "confidence" field if the given value is not nil.
func (_c *SecurityEventCreate) SetNillableConfidence(v *float64) *SecurityEventCreate {
	if v != nil {
		_c.SetConfidence(*v)
	}
	return _c
}

// SetRequestSnapshot sets the "request_snapshot" field.
func (_c *SecurityEventCreate) SetRequestSnapshot(v string) *SecurityEventCreate {
	_c.mutation.SetRequestSnapshot(v)
	return _c
}

// SetNillableRequestSnapshot sets the "request_snapshot" field if the given value is not nil.
func (_c *SecurityEventCreate) SetNillableRequestSnapshot(v *string) *SecurityEventCreate {
	if v != nil {
		_c.SetRequestSnapshot(*v)
	}
	return _c
}

// SetSourceIP sets the "source_ip" field.
func (_c *SecurityEventCreate) SetSourceIP(v string) *SecurityEventCreate {
	_c.mutation.SetSourceIP(v)
	return _c
}

// SetNillableSourceIP sets the "source_ip" field if the given value is not nil.
func (_c *SecurityEventCreate) SetNillableSourceIP(v *string) *SecurityEventCreate {
	if v != nil {
		_c.SetSourceIP(*v)
	}
	return _c
}

// SetUserAgent sets the "user_agent" field.
func (_c *SecurityEventCreate) SetUserAgent(v string) *SecurityEventCreate {
	_c.mutation.SetUserAgent(v)
	return _c
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_c *SecurityEventCreate) SetNillableUserAgent(v *string) *SecurityEventCreate {
	if v != nil {
		_c.SetUserAgent(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *SecurityEventCreate) SetStatus(v string) *SecurityEventCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SecurityEventCreate) SetNillableStatus(v *string) *SecurityEventCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetResolution sets the "resolution" field.
func (_c *SecurityEventCreate) SetResolution(v string) *SecurityEventCreate {
	_c.mutation.SetResolution(v)
	return _c
}

// SetNillableResolution sets the "resolution" field if the given value is not nil.
func (_c *SecurityEventCreate) SetNillableResolution(v *string) *SecurityEventCreate {
	if v != nil {
		_c.SetResolution(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SecurityEventCreate) SetCreatedAt(v time.Time) *SecurityEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SecurityEventCreate) SetNillableCreatedAt(v *time.Time) *SecurityEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetResolvedAt sets the "resolved_at" field.
func (_c *SecurityEventCreate) SetResolvedAt(v time.Time) *SecurityEventCreate {
	_c.mutation.SetResolvedAt(v)
	return _c
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (_c *SecurityEventCreate) SetNillableResolvedAt(v *time.Time) *SecurityEventCreate {
	if v != nil {
		_c.SetResolvedAt(*v)
	}
	return _c
}

// Mutation returns the SecurityEventMutation object of the builder.
func (_c *SecurityEventCreate) Mutation() *SecurityEventMutation {
	return _c.mutation
}

// Save creates the SecurityEvent in the database.
func (_c *SecurityEventCreate) Save(ctx context.Context) (*SecurityEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SecurityEventCreate) SaveX(ctx context.Context) *SecurityEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SecurityEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SecurityEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SecurityEventCreate) defaults() {
	if _, ok := _c.mutation.Action(); !ok {
		v := securityevent.DefaultAction
		_c.mutation.SetAction(v)
	}
	if _, ok := _c.mutation.Confidence(); !ok {
		v := securityevent.DefaultConfidence
		_c.mutation.SetConfidence(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := securityevent.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := securityevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SecurityEventCreate) check() error {
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "SecurityEvent.event_type"`)}
	}
	if v, ok := _c.mutation.EventType(); ok {
		if err := securityevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "SecurityEvent.event_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Severity(); !ok {
		return &ValidationError{Name: "severity", err: errors.New(`ent: missing required field "SecurityEvent.severity"`)}
	}
	if v, ok := _c.mutation.Severity(); ok {
		if err := securityevent.SeverityValidator(v); err != nil {
			return &ValidationError{Name: "severity", err: fmt.Errorf(`ent: validator failed for field "SecurityEvent.severity": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "SecurityEvent.category"`)}
	}
	if v, ok := _c.mutation.Category(); ok {
		if err := securityevent.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "SecurityEvent.category": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "SecurityEvent.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := securityevent.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "SecurityEvent.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "SecurityEvent.description"`)}
	}
	if v, ok := _c.mutation.RequestID(); ok {
		if err := securityevent.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "SecurityEvent.request_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := securityevent.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "SecurityEvent.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "SecurityEvent.action"`)}
	}
	if v, ok := _c.mutation.Action(); ok {
		if err := securityevent.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "SecurityEvent.action": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Confidence(); !ok {
		return &ValidationError{Name: "confidence", err: errors.New(`ent: missing required field "SecurityEvent.confidence"`)}
	}
	if v, ok := _c.mutation.SourceIP(); ok {
		if err := securityevent.SourceIPValidator(v); err != nil {
			return &ValidationError{Name: "source_ip", err: fmt.Errorf(`ent: validator failed for field "SecurityEvent.source_ip": %w`, err)}
		}
	}
	if v, ok := _c.mutation.UserAgent(); ok {
		if err := securityevent.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "SecurityEvent.user_agent": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SecurityEvent.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := securityevent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SecurityEvent.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SecurityEvent.created_at"`)}
	}
	return nil
}

func (_c *SecurityEventCreate) sqlSave(ctx context.Context) (*SecurityEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SecurityEventCreate) createSpec() (*SecurityEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &SecurityEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(securityevent.Table, sqlgraph.NewFieldSpec(securityevent.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(securityevent.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.Severity(); ok {
		_spec.SetField(securityevent.FieldSeverity, field.TypeString, value)
		_node.Severity = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(securityevent.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(securityevent.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(securityevent.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(securityevent.FieldUserID, field.TypeInt64, value)
		_node.UserID = &value
	}
	if value, ok := _c.mutation.APIKeyID(); ok {
		_spec.SetField(securityevent.FieldAPIKeyID, field.TypeInt64, value)
		_node.APIKeyID = &value
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(securityevent.FieldRequestID, field.TypeString, value)
		_node.RequestID = &value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(securityevent.FieldModel, field.TypeString, value)
		_node.Model = &value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(securityevent.FieldAction, field.TypeString, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.MatchedPatterns(); ok {
		_spec.SetField(securityevent.FieldMatchedPatterns, field.TypeString, value)
		_node.MatchedPatterns = &value
	}
	if value, ok := _c.mutation.Confidence(); ok {
		_spec.SetField(securityevent.FieldConfidence, field.TypeFloat64, value)
		_node.Confidence = value
	}
	if value, ok := _c.mutation.RequestSnapshot(); ok {
		_spec.SetField(securityevent.FieldRequestSnapshot, field.TypeString, value)
		_node.RequestSnapshot = &value
	}
	if value, ok := _c.mutation.SourceIP(); ok {
		_spec.SetField(securityevent.FieldSourceIP, field.TypeString, value)
		_node.SourceIP = &value
	}
	if value, ok := _c.mutation.UserAgent(); ok {
		_spec.SetField(securityevent.FieldUserAgent, field.TypeString, value)
		_node.UserAgent = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(securityevent.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Resolution(); ok {
		_spec.SetField(securityevent.FieldResolution, field.TypeString, value)
		_node.Resolution = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(securityevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.ResolvedAt(); ok {
		_spec.SetField(securityevent.FieldResolvedAt, field.TypeTime, value)
		_node.ResolvedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SecurityEvent.Create().
//		SetEventType(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SecurityEventUpsert) {
//			SetEventType(v+v).
//		}).
//		Exec(ctx)
func (_c *SecurityEventCreate) OnConflict(opts ...sql.ConflictOption) *SecurityEventUpsertOne {
	_c.conflict = opts
	return &SecurityEventUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SecurityEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SecurityEventCreate) OnConflictColumns(columns ...string) *SecurityEventUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SecurityEventUpsertOne{
		create: _c,
	}
}

type (
	// SecurityEventUpsertOne is the builder for "upsert"-ing
	//  one SecurityEvent node.
	SecurityEventUpsertOne struct {
		create *SecurityEventCreate
	}

	// SecurityEventUpsert is the "OnConflict" setter.
	SecurityEventUpsert struct {
		*sql.UpdateSet
	}
)

// SetEventType sets the "event_type" field.
func (u *SecurityEventUpsert) SetEventType(v string) *SecurityEventUpsert {
	u.Set(securityevent.FieldEventType, v)
	return u
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *SecurityEventUpsert) UpdateEventType() *SecurityEventUpsert {
	u.SetExcluded(securityevent.FieldEventType)
	return u
}

// SetSeverity sets the "severity" field.
func (u *SecurityEventUpsert) SetSeverity(v string) *SecurityEventUpsert {
	u.Set(securityevent.FieldSeverity, v)
	return u
}

// UpdateSeverity sets the "severity" field to the value that was provided on create.
func (u *SecurityEventUpsert) UpdateSeverity() *SecurityEventUpsert {
	u.SetExcluded(securityevent.FieldSeverity)
	return u
}

// SetCategory sets the "category" field.
func (u *SecurityEventUpsert) SetCategory(v string) *SecurityEventUpsert {
	u.Set(securityevent.FieldCategory, v)
	return u
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *SecurityEventUpsert) UpdateCategory() *SecurityEventUpsert {
	u.SetExcluded(securityevent.FieldCategory)
	return u
}

// SetTitle sets the "title" field.
func (u *SecurityEventUpsert) SetTitle(v string) *SecurityEventUpsert {
	u.Set(securityevent.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *SecurityEventUpsert) UpdateTitle() *SecurityEventUpsert {
	u.SetExcluded(securityevent.FieldTitle)
	return u
}

// SetDescription sets the "description" field.
func (u *SecurityEventUpsert) SetDescription(v string) *SecurityEventUpsert {
	u.Set(securityevent.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SecurityEventUpsert) UpdateDescription() *SecurityEventUpsert {
	u.SetExcluded(securityevent.FieldDescription)
	return u
}

// SetUserID sets the "user_id" field.
func (u *SecurityEventUpsert) SetUserID(v int64) *SecurityEventUpsert {
	u.Set(securityevent.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SecurityEventUpsert) UpdateUserID() *SecurityEventUpsert {
	u.SetExcluded(securityevent.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *SecurityEventUpsert) AddUserID(v int64) *SecurityEventUpsert {
	u.Add(securityevent.FieldUserID, v)
	return u
}

// ClearUserID clears the value of the "user_id" field.
func (u *SecurityEventUpsert) ClearUserID() *SecurityEventUpsert {
	u.SetNull(securityevent.FieldUserID)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *SecurityEventUpsert) SetAPIKeyID(v int64) *SecurityEventUpsert {
	u.Set(securityevent.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *SecurityEventUpsert) UpdateAPIKeyID() *SecurityEventUpsert {
	u.SetExcluded(securityevent.FieldAPIKeyID)
	return u
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *SecurityEventUpsert) AddAPIKeyID(v int64) *SecurityEventUpsert {
	u.Add(securityevent.FieldAPIKeyID, v)
	return u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *SecurityEventUpsert) ClearAPIKeyID() *SecurityEventUpsert {
	u.SetNull(securityevent.FieldAPIKeyID)
	return u
}

// SetRequestID sets the "request_id" field.
func (u *SecurityEventUpsert) SetRequestID(v string) *SecurityEventUpsert {
	u.Set(securityevent.FieldRequestID, v)
	return u
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *SecurityEventUpsert) UpdateRequestID() *SecurityEventUpsert {
	u.SetExcluded(securityevent.FieldRequestID)
	return u
}

// ClearRequestID clears the value of the "request_id" field.
func (u *SecurityEventUpsert) ClearRequestID() *SecurityEventUpsert {
	u.SetNull(securityevent.FieldRequestID)
	return u
}

// SetModel sets the "model" field.
func (u *SecurityEventUpsert) SetModel(v string) *SecurityEventUpsert {
	u.Set(securityevent.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *SecurityEventUpsert) UpdateModel() *SecurityEventUpsert {
	u.SetExcluded(securityevent.FieldModel)
	return u
}

// ClearModel clears the value of the "model" field.
func (u *SecurityEventUpsert) ClearModel() *SecurityEventUpsert {
	u.SetNull(securityevent.FieldModel)
	return u
}

// SetAction sets the "action" field.
func (u *SecurityEventUpsert) SetAction(v string) *SecurityEventUpsert {
	u.Set(securityevent.FieldAction, v)
	return u
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *SecurityEventUpsert) UpdateAction() *SecurityEventUpsert {
	u.SetExcluded(securityevent.FieldAction)
	return u
}

// SetMatchedPatterns sets the "matched_patterns" field.
func (u *SecurityEventUpsert) SetMatchedPatterns(v string) *SecurityEventUpsert {
	u.Set(securityevent.FieldMatchedPatterns, v)
	return u
}

// UpdateMatchedPatterns sets the "matched_patterns" field to the value that was provided on create.
func (u *SecurityEventUpsert) UpdateMatchedPatterns() *SecurityEventUpsert {
	u.SetExcluded(securityevent.FieldMatchedPatterns)
	return u
}

// ClearMatchedPatterns clears the value of the "matched_patterns" field.
func (u *SecurityEventUpsert) ClearMatchedPatterns() *SecurityEventUpsert {
	u.SetNull(securityevent.FieldMatchedPatterns)
	return u
}

// SetConfidence sets the "confidence" field.
func (u *SecurityEventUpsert) SetConfidence(v float64) *SecurityEventUpsert {
	u.Set(securityevent.FieldConfidence, v)
	return u
}

// UpdateConfidence sets the "confidence" field to the value that was provided on create.
func (u *SecurityEventUpsert) UpdateConfidence() *SecurityEventUpsert {
	u.SetExcluded(securityevent.FieldConfidence)
	return u
}

// AddConfidence adds v to the "confidence" field.
func (u *SecurityEventUpsert) AddConfidence(v float64) *SecurityEventUpsert {
	u.Add(securityevent.FieldConfidence, v)
	return u
}

// SetRequestSnapshot sets the "request_snapshot" field.
func (u *SecurityEventUpsert) SetRequestSnapshot(v string) *SecurityEventUpsert {
	u.Set(securityevent.FieldRequestSnapshot, v)
	return u
}

// UpdateRequestSnapshot sets the "request_snapshot" field to the value that was provided on create.
func (u *SecurityEventUpsert) UpdateRequestSnapshot() *SecurityEventUpsert {
	u.SetExcluded(securityevent.FieldRequestSnapshot)
	return u
}

// ClearRequestSnapshot clears the value of the "request_snapshot" field.
func (u *SecurityEventUpsert) ClearRequestSnapshot() *SecurityEventUpsert {
	u.SetNull(securityevent.FieldRequestSnapshot)
	return u
}

// SetSourceIP sets the "source_ip" field.
func (u *SecurityEventUpsert) SetSourceIP(v string) *SecurityEventUpsert {
	u.Set(securityevent.FieldSourceIP, v)
	return u
}

// UpdateSourceIP sets the "source_ip" field to the value that was provided on create.
func (u *SecurityEventUpsert) UpdateSourceIP() *SecurityEventUpsert {
	u.SetExcluded(securityevent.FieldSourceIP)
	return u
}

// ClearSourceIP clears the value of the "source_ip" field.
func (u *SecurityEventUpsert) ClearSourceIP() *SecurityEventUpsert {
	u.SetNull(securityevent.FieldSourceIP)
	return u
}

// SetUserAgent sets the "user_agent" field.
func (u *SecurityEventUpsert) SetUserAgent(v string) *SecurityEventUpsert {
	u.Set(securityevent.FieldUserAgent, v)
	return u
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *SecurityEventUpsert) UpdateUserAgent() *SecurityEventUpsert {
	u.SetExcluded(securityevent.FieldUserAgent)
	return u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (u *SecurityEventUpsert) ClearUserAgent() *SecurityEventUpsert {
	u.SetNull(securityevent.FieldUserAgent)
	return u
}

// SetStatus sets the "status" field.
func (u *SecurityEventUpsert) SetStatus(v string) *SecurityEventUpsert {
	u.Set(securityevent.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SecurityEventUpsert) UpdateStatus() *SecurityEventUpsert {
	u.SetExcluded(securityevent.FieldStatus)
	return u
}

// SetResolution sets the "resolution" field.
func (u *SecurityEventUpsert) SetResolution(v string) *SecurityEventUpsert {
	u.Set(securityevent.FieldResolution, v)
	return u
}

// UpdateResolution sets the "resolution" field to the value that was provided on create.
func (u *SecurityEventUpsert) UpdateResolution() *SecurityEventUpsert {
	u.SetExcluded(securityevent.FieldResolution)
	return u
}

// ClearResolution clears the value of the "resolution" field.
func (u *SecurityEventUpsert) ClearResolution() *SecurityEventUpsert {
	u.SetNull(securityevent.FieldResolution)
	return u
}

// SetResolvedAt sets the "resolved_at" field.
func (u *SecurityEventUpsert) SetResolvedAt(v time.Time) *SecurityEventUpsert {
	u.Set(securityevent.FieldResolvedAt, v)
	return u
}

// UpdateResolvedAt sets the "resolved_at" field to the value that was provided on create.
func (u *SecurityEventUpsert) UpdateResolvedAt() *SecurityEventUpsert {
	u.SetExcluded(securityevent.FieldResolvedAt)
	return u
}

// ClearResolvedAt clears the value of the "resolved_at" field.
func (u *SecurityEventUpsert) ClearResolvedAt() *SecurityEventUpsert {
	u.SetNull(securityevent.FieldResolvedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SecurityEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SecurityEventUpsertOne) UpdateNewValues() *SecurityEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(securityevent.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SecurityEvent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SecurityEventUpsertOne) Ignore() *SecurityEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SecurityEventUpsertOne) DoNothing() *SecurityEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SecurityEventCreate.OnConflict
// documentation for more info.
func (u *SecurityEventUpsertOne) Update(set func(*SecurityEventUpsert)) *SecurityEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SecurityEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetEventType sets the "event_type" field.
func (u *SecurityEventUpsertOne) SetEventType(v string) *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetEventType(v)
	})
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *SecurityEventUpsertOne) UpdateEventType() *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateEventType()
	})
}

// SetSeverity sets the "severity" field.
func (u *SecurityEventUpsertOne) SetSeverity(v string) *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetSeverity(v)
	})
}

// UpdateSeverity sets the "severity" field to the value that was provided on create.
func (u *SecurityEventUpsertOne) UpdateSeverity() *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateSeverity()
	})
}

// SetCategory sets the "category" field.
func (u *SecurityEventUpsertOne) SetCategory(v string) *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *SecurityEventUpsertOne) UpdateCategory() *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateCategory()
	})
}

// SetTitle sets the "title" field.
func (u *SecurityEventUpsertOne) SetTitle(v string) *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *SecurityEventUpsertOne) UpdateTitle() *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateTitle()
	})
}

// SetDescription sets the "description" field.
func (u *SecurityEventUpsertOne) SetDescription(v string) *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SecurityEventUpsertOne) UpdateDescription() *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateDescription()
	})
}

// SetUserID sets the "user_id" field.
func (u *SecurityEventUpsertOne) SetUserID(v int64) *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *SecurityEventUpsertOne) AddUserID(v int64) *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SecurityEventUpsertOne) UpdateUserID() *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *SecurityEventUpsertOne) ClearUserID() *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.ClearUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *SecurityEventUpsertOne) SetAPIKeyID(v int64) *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *SecurityEventUpsertOne) AddAPIKeyID(v int64) *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *SecurityEventUpsertOne) UpdateAPIKeyID() *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateAPIKeyID()
	})
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *SecurityEventUpsertOne) ClearAPIKeyID() *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.ClearAPIKeyID()
	})
}

// SetRequestID sets the "request_id" field.
func (u *SecurityEventUpsertOne) SetRequestID(v string) *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *SecurityEventUpsertOne) UpdateRequestID() *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateRequestID()
	})
}

// ClearRequestID clears the value of the "request_id" field.
func (u *SecurityEventUpsertOne) ClearRequestID() *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.ClearRequestID()
	})
}

// SetModel sets the "model" field.
func (u *SecurityEventUpsertOne) SetModel(v string) *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *SecurityEventUpsertOne) UpdateModel() *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateModel()
	})
}

// ClearModel clears the value of the "model" field.
func (u *SecurityEventUpsertOne) ClearModel() *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.ClearModel()
	})
}

// SetAction sets the "action" field.
func (u *SecurityEventUpsertOne) SetAction(v string) *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *SecurityEventUpsertOne) UpdateAction() *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateAction()
	})
}

// SetMatchedPatterns sets the "matched_patterns" field.
func (u *SecurityEventUpsertOne) SetMatchedPatterns(v string) *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetMatchedPatterns(v)
	})
}

// UpdateMatchedPatterns sets the "matched_patterns" field to the value that was provided on create.
func (u *SecurityEventUpsertOne) UpdateMatchedPatterns() *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateMatchedPatterns()
	})
}

// ClearMatchedPatterns clears the value of the "matched_patterns" field.
func (u *SecurityEventUpsertOne) ClearMatchedPatterns() *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.ClearMatchedPatterns()
	})
}

// SetConfidence sets the "confidence" field.
func (u *SecurityEventUpsertOne) SetConfidence(v float64) *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetConfidence(v)
	})
}

// AddConfidence adds v to the "confidence" field.
func (u *SecurityEventUpsertOne) AddConfidence(v float64) *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.AddConfidence(v)
	})
}

// UpdateConfidence sets the "confidence" field to the value that was provided on create.
func (u *SecurityEventUpsertOne) UpdateConfidence() *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateConfidence()
	})
}

// SetRequestSnapshot sets the "request_snapshot" field.
func (u *SecurityEventUpsertOne) SetRequestSnapshot(v string) *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetRequestSnapshot(v)
	})
}

// UpdateRequestSnapshot sets the "request_snapshot" field to the value that was provided on create.
func (u *SecurityEventUpsertOne) UpdateRequestSnapshot() *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateRequestSnapshot()
	})
}

// ClearRequestSnapshot clears the value of the "request_snapshot" field.
func (u *SecurityEventUpsertOne) ClearRequestSnapshot() *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.ClearRequestSnapshot()
	})
}

// SetSourceIP sets the "source_ip" field.
func (u *SecurityEventUpsertOne) SetSourceIP(v string) *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetSourceIP(v)
	})
}

// UpdateSourceIP sets the "source_ip" field to the value that was provided on create.
func (u *SecurityEventUpsertOne) UpdateSourceIP() *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateSourceIP()
	})
}

// ClearSourceIP clears the value of the "source_ip" field.
func (u *SecurityEventUpsertOne) ClearSourceIP() *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.ClearSourceIP()
	})
}

// SetUserAgent sets the "user_agent" field.
func (u *SecurityEventUpsertOne) SetUserAgent(v string) *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetUserAgent(v)
	})
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *SecurityEventUpsertOne) UpdateUserAgent() *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateUserAgent()
	})
}

// ClearUserAgent clears the value of the "user_agent" field.
func (u *SecurityEventUpsertOne) ClearUserAgent() *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.ClearUserAgent()
	})
}

// SetStatus sets the "status" field.
func (u *SecurityEventUpsertOne) SetStatus(v string) *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SecurityEventUpsertOne) UpdateStatus() *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateStatus()
	})
}

// SetResolution sets the "resolution" field.
func (u *SecurityEventUpsertOne) SetResolution(v string) *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetResolution(v)
	})
}

// UpdateResolution sets the "resolution" field to the value that was provided on create.
func (u *SecurityEventUpsertOne) UpdateResolution() *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateResolution()
	})
}

// ClearResolution clears the value of the "resolution" field.
func (u *SecurityEventUpsertOne) ClearResolution() *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.ClearResolution()
	})
}

// SetResolvedAt sets the "resolved_at" field.
func (u *SecurityEventUpsertOne) SetResolvedAt(v time.Time) *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetResolvedAt(v)
	})
}

// UpdateResolvedAt sets the "resolved_at" field to the value that was provided on create.
func (u *SecurityEventUpsertOne) UpdateResolvedAt() *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateResolvedAt()
	})
}

// ClearResolvedAt clears the value of the "resolved_at" field.
func (u *SecurityEventUpsertOne) ClearResolvedAt() *SecurityEventUpsertOne {
	return u.Update(func(s *SecurityEventUpsert) {
		s.ClearResolvedAt()
	})
}

// Exec executes the query.
func (u *SecurityEventUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SecurityEventCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SecurityEventUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SecurityEventUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SecurityEventUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SecurityEventCreateBulk is the builder for creating many SecurityEvent entities in bulk.
type SecurityEventCreateBulk struct {
	config
	err      error
	builders []*SecurityEventCreate
	conflict []sql.ConflictOption
}

// Save creates the SecurityEvent entities in the database.
func (_c *SecurityEventCreateBulk) Save(ctx context.Context) ([]*SecurityEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SecurityEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SecurityEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SecurityEventCreateBulk) SaveX(ctx context.Context) []*SecurityEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SecurityEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SecurityEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SecurityEvent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SecurityEventUpsert) {
//			SetEventType(v+v).
//		}).
//		Exec(ctx)
func (_c *SecurityEventCreateBulk) OnConflict(opts ...sql.ConflictOption) *SecurityEventUpsertBulk {
	_c.conflict = opts
	return &SecurityEventUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SecurityEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SecurityEventCreateBulk) OnConflictColumns(columns ...string) *SecurityEventUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SecurityEventUpsertBulk{
		create: _c,
	}
}

// SecurityEventUpsertBulk is the builder for "upsert"-ing
// a bulk of SecurityEvent nodes.
type SecurityEventUpsertBulk struct {
	create *SecurityEventCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SecurityEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SecurityEventUpsertBulk) UpdateNewValues() *SecurityEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(securityevent.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SecurityEvent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SecurityEventUpsertBulk) Ignore() *SecurityEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SecurityEventUpsertBulk) DoNothing() *SecurityEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SecurityEventCreateBulk.OnConflict
// documentation for more info.
func (u *SecurityEventUpsertBulk) Update(set func(*SecurityEventUpsert)) *SecurityEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SecurityEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetEventType sets the "event_type" field.
func (u *SecurityEventUpsertBulk) SetEventType(v string) *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetEventType(v)
	})
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *SecurityEventUpsertBulk) UpdateEventType() *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateEventType()
	})
}

// SetSeverity sets the "severity" field.
func (u *SecurityEventUpsertBulk) SetSeverity(v string) *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetSeverity(v)
	})
}

// UpdateSeverity sets the "severity" field to the value that was provided on create.
func (u *SecurityEventUpsertBulk) UpdateSeverity() *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateSeverity()
	})
}

// SetCategory sets the "category" field.
func (u *SecurityEventUpsertBulk) SetCategory(v string) *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *SecurityEventUpsertBulk) UpdateCategory() *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateCategory()
	})
}

// SetTitle sets the "title" field.
func (u *SecurityEventUpsertBulk) SetTitle(v string) *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *SecurityEventUpsertBulk) UpdateTitle() *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateTitle()
	})
}

// SetDescription sets the "description" field.
func (u *SecurityEventUpsertBulk) SetDescription(v string) *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SecurityEventUpsertBulk) UpdateDescription() *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateDescription()
	})
}

// SetUserID sets the "user_id" field.
func (u *SecurityEventUpsertBulk) SetUserID(v int64) *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *SecurityEventUpsertBulk) AddUserID(v int64) *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SecurityEventUpsertBulk) UpdateUserID() *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *SecurityEventUpsertBulk) ClearUserID() *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.ClearUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *SecurityEventUpsertBulk) SetAPIKeyID(v int64) *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *SecurityEventUpsertBulk) AddAPIKeyID(v int64) *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *SecurityEventUpsertBulk) UpdateAPIKeyID() *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateAPIKeyID()
	})
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *SecurityEventUpsertBulk) ClearAPIKeyID() *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.ClearAPIKeyID()
	})
}

// SetRequestID sets the "request_id" field.
func (u *SecurityEventUpsertBulk) SetRequestID(v string) *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *SecurityEventUpsertBulk) UpdateRequestID() *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateRequestID()
	})
}

// ClearRequestID clears the value of the "request_id" field.
func (u *SecurityEventUpsertBulk) ClearRequestID() *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.ClearRequestID()
	})
}

// SetModel sets the "model" field.
func (u *SecurityEventUpsertBulk) SetModel(v string) *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *SecurityEventUpsertBulk) UpdateModel() *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateModel()
	})
}

// ClearModel clears the value of the "model" field.
func (u *SecurityEventUpsertBulk) ClearModel() *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.ClearModel()
	})
}

// SetAction sets the "action" field.
func (u *SecurityEventUpsertBulk) SetAction(v string) *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *SecurityEventUpsertBulk) UpdateAction() *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateAction()
	})
}

// SetMatchedPatterns sets the "matched_patterns" field.
func (u *SecurityEventUpsertBulk) SetMatchedPatterns(v string) *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetMatchedPatterns(v)
	})
}

// UpdateMatchedPatterns sets the "matched_patterns" field to the value that was provided on create.
func (u *SecurityEventUpsertBulk) UpdateMatchedPatterns() *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateMatchedPatterns()
	})
}

// ClearMatchedPatterns clears the value of the "matched_patterns" field.
func (u *SecurityEventUpsertBulk) ClearMatchedPatterns() *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.ClearMatchedPatterns()
	})
}

// SetConfidence sets the "confidence" field.
func (u *SecurityEventUpsertBulk) SetConfidence(v float64) *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetConfidence(v)
	})
}

// AddConfidence adds v to the "confidence" field.
func (u *SecurityEventUpsertBulk) AddConfidence(v float64) *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.AddConfidence(v)
	})
}

// UpdateConfidence sets the "confidence" field to the value that was provided on create.
func (u *SecurityEventUpsertBulk) UpdateConfidence() *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateConfidence()
	})
}

// SetRequestSnapshot sets the "request_snapshot" field.
func (u *SecurityEventUpsertBulk) SetRequestSnapshot(v string) *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetRequestSnapshot(v)
	})
}

// UpdateRequestSnapshot sets the "request_snapshot" field to the value that was provided on create.
func (u *SecurityEventUpsertBulk) UpdateRequestSnapshot() *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateRequestSnapshot()
	})
}

// ClearRequestSnapshot clears the value of the "request_snapshot" field.
func (u *SecurityEventUpsertBulk) ClearRequestSnapshot() *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.ClearRequestSnapshot()
	})
}

// SetSourceIP sets the "source_ip" field.
func (u *SecurityEventUpsertBulk) SetSourceIP(v string) *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetSourceIP(v)
	})
}

// UpdateSourceIP sets the "source_ip" field to the value that was provided on create.
func (u *SecurityEventUpsertBulk) UpdateSourceIP() *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateSourceIP()
	})
}

// ClearSourceIP clears the value of the "source_ip" field.
func (u *SecurityEventUpsertBulk) ClearSourceIP() *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.ClearSourceIP()
	})
}

// SetUserAgent sets the "user_agent" field.
func (u *SecurityEventUpsertBulk) SetUserAgent(v string) *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetUserAgent(v)
	})
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *SecurityEventUpsertBulk) UpdateUserAgent() *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateUserAgent()
	})
}

// ClearUserAgent clears the value of the "user_agent" field.
func (u *SecurityEventUpsertBulk) ClearUserAgent() *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.ClearUserAgent()
	})
}

// SetStatus sets the "status" field.
func (u *SecurityEventUpsertBulk) SetStatus(v string) *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SecurityEventUpsertBulk) UpdateStatus() *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateStatus()
	})
}

// SetResolution sets the "resolution" field.
func (u *SecurityEventUpsertBulk) SetResolution(v string) *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetResolution(v)
	})
}

// UpdateResolution sets the "resolution" field to the value that was provided on create.
func (u *SecurityEventUpsertBulk) UpdateResolution() *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateResolution()
	})
}

// ClearResolution clears the value of the "resolution" field.
func (u *SecurityEventUpsertBulk) ClearResolution() *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.ClearResolution()
	})
}

// SetResolvedAt sets the "resolved_at" field.
func (u *SecurityEventUpsertBulk) SetResolvedAt(v time.Time) *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.SetResolvedAt(v)
	})
}

// UpdateResolvedAt sets the "resolved_at" field to the value that was provided on create.
func (u *SecurityEventUpsertBulk) UpdateResolvedAt() *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.UpdateResolvedAt()
	})
}

// ClearResolvedAt clears the value of the "resolved_at" field.
func (u *SecurityEventUpsertBulk) ClearResolvedAt() *SecurityEventUpsertBulk {
	return u.Update(func(s *SecurityEventUpsert) {
		s.ClearResolvedAt()
	})
}

// Exec executes the query.
func (u *SecurityEventUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SecurityEventCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SecurityEventCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SecurityEventUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
