// Code generated by ent, DO NOT EDIT.

package dlprule

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the dlprule type in the database.
	Label = "dlp_rule"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldCategory holds the string denoting the category field in the database.
	FieldCategory = "category"
	// FieldPattern holds the string denoting the pattern field in the database.
	FieldPattern = "pattern"
	// FieldPatternType holds the string denoting the pattern_type field in the database.
	FieldPatternType = "pattern_type"
	// FieldSeverity holds the string denoting the severity field in the database.
	FieldSeverity = "severity"
	// FieldAction holds the string denoting the action field in the database.
	FieldAction = "action"
	// FieldMaskContent holds the string denoting the mask_content field in the database.
	FieldMaskContent = "mask_content"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldScope holds the string denoting the scope field in the database.
	FieldScope = "scope"
	// FieldModels holds the string denoting the models field in the database.
	FieldModels = "models"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the dlprule in the database.
	Table = "dlp_rules"
)

// Columns holds all SQL columns for dlprule fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldCategory,
	FieldPattern,
	FieldPatternType,
	FieldSeverity,
	FieldAction,
	FieldMaskContent,
	FieldEnabled,
	FieldPriority,
	FieldScope,
	FieldModels,
	FieldMetadata,
	FieldCreatedBy,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// CategoryValidator is a validator for the "category" field. It is called by the builders before save.
	CategoryValidator func(string) error
	// PatternValidator is a validator for the "pattern" field. It is called by the builders before save.
	PatternValidator func(string) error
	// DefaultPatternType holds the default value on creation for the "pattern_type" field.
	DefaultPatternType string
	// PatternTypeValidator is a validator for the "pattern_type" field. It is called by the builders before save.
	PatternTypeValidator func(string) error
	// DefaultSeverity holds the default value on creation for the "severity" field.
	DefaultSeverity string
	// SeverityValidator is a validator for the "severity" field. It is called by the builders before save.
	SeverityValidator func(string) error
	// DefaultAction holds the default value on creation for the "action" field.
	DefaultAction string
	// ActionValidator is a validator for the "action" field. It is called by the builders before save.
	ActionValidator func(string) error
	// DefaultMaskContent holds the default value on creation for the "mask_content" field.
	DefaultMaskContent bool
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultPriority holds the default value on creation for the "priority" field.
	DefaultPriority int
	// DefaultScope holds the default value on creation for the "scope" field.
	DefaultScope string
	// ScopeValidator is a validator for the "scope" field. It is called by the builders before save.
	ScopeValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the DLPRule queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByCategory orders the results by the category field.
func ByCategory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategory, opts...).ToFunc()
}

// ByPattern orders the results by the pattern field.
func ByPattern(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPattern, opts...).ToFunc()
}

// ByPatternType orders the results by the pattern_type field.
func ByPatternType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPatternType, opts...).ToFunc()
}

// BySeverity orders the results by the severity field.
func BySeverity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeverity, opts...).ToFunc()
}

// ByAction orders the results by the action field.
func ByAction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAction, opts...).ToFunc()
}

// ByMaskContent orders the results by the mask_content field.
func ByMaskContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaskContent, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByScope orders the results by the scope field.
func ByScope(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScope, opts...).ToFunc()
}

// ByModels orders the results by the models field.
func ByModels(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModels, opts...).ToFunc()
}

// ByMetadata orders the results by the metadata field.
func ByMetadata(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetadata, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
