// Code generated by ent, DO NOT EDIT.

package dlprule

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEQ(FieldDescription, v))
}

// Category applies equality check predicate on the "category" field. It's identical to CategoryEQ.
func Category(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEQ(FieldCategory, v))
}

// Pattern applies equality check predicate on the "pattern" field. It's identical to PatternEQ.
func Pattern(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEQ(FieldPattern, v))
}

// PatternType applies equality check predicate on the "pattern_type" field. It's identical to PatternTypeEQ.
func PatternType(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEQ(FieldPatternType, v))
}

// Severity applies equality check predicate on the "severity" field. It's identical to SeverityEQ.
func Severity(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEQ(FieldSeverity, v))
}

// Action applies equality check predicate on the "action" field. It's identical to ActionEQ.
func Action(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEQ(FieldAction, v))
}

// MaskContent applies equality check predicate on the "mask_content" field. It's identical to MaskContentEQ.
func MaskContent(v bool) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEQ(FieldMaskContent, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEQ(FieldEnabled, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v int) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEQ(FieldPriority, v))
}

// Scope applies equality check predicate on the "scope" field. It's identical to ScopeEQ.
func Scope(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEQ(FieldScope, v))
}

// Models applies equality check predicate on the "models" field. It's identical to ModelsEQ.
func Models(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEQ(FieldModels, v))
}

// Metadata applies equality check predicate on the "metadata" field. It's identical to MetadataEQ.
func Metadata(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEQ(FieldMetadata, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v int64) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldContainsFold(FieldDescription, v))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldNotIn(FieldCategory, vs...))
}

// CategoryGT applies the GT predicate on the "category" field.
func CategoryGT(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldGT(FieldCategory, v))
}

// CategoryGTE applies the GTE predicate on the "category" field.
func CategoryGTE(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldGTE(FieldCategory, v))
}

// CategoryLT applies the LT predicate on the "category" field.
func CategoryLT(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldLT(FieldCategory, v))
}

// CategoryLTE applies the LTE predicate on the "category" field.
func CategoryLTE(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldLTE(FieldCategory, v))
}

// CategoryContains applies the Contains predicate on the "category" field.
func CategoryContains(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldContains(FieldCategory, v))
}

// CategoryHasPrefix applies the HasPrefix predicate on the "category" field.
func CategoryHasPrefix(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldHasPrefix(FieldCategory, v))
}

// CategoryHasSuffix applies the HasSuffix predicate on the "category" field.
func CategoryHasSuffix(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldHasSuffix(FieldCategory, v))
}

// CategoryEqualFold applies the EqualFold predicate on the "category" field.
func CategoryEqualFold(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEqualFold(FieldCategory, v))
}

// CategoryContainsFold applies the ContainsFold predicate on the "category" field.
func CategoryContainsFold(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldContainsFold(FieldCategory, v))
}

// PatternEQ applies the EQ predicate on the "pattern" field.
func PatternEQ(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEQ(FieldPattern, v))
}

// PatternNEQ applies the NEQ predicate on the "pattern" field.
func PatternNEQ(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldNEQ(FieldPattern, v))
}

// PatternIn applies the In predicate on the "pattern" field.
func PatternIn(vs ...string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldIn(FieldPattern, vs...))
}

// PatternNotIn applies the NotIn predicate on the "pattern" field.
func PatternNotIn(vs ...string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldNotIn(FieldPattern, vs...))
}

// PatternGT applies the GT predicate on the "pattern" field.
func PatternGT(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldGT(FieldPattern, v))
}

// PatternGTE applies the GTE predicate on the "pattern" field.
func PatternGTE(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldGTE(FieldPattern, v))
}

// PatternLT applies the LT predicate on the "pattern" field.
func PatternLT(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldLT(FieldPattern, v))
}

// PatternLTE applies the LTE predicate on the "pattern" field.
func PatternLTE(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldLTE(FieldPattern, v))
}

// PatternContains applies the Contains predicate on the "pattern" field.
func PatternContains(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldContains(FieldPattern, v))
}

// PatternHasPrefix applies the HasPrefix predicate on the "pattern" field.
func PatternHasPrefix(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldHasPrefix(FieldPattern, v))
}

// PatternHasSuffix applies the HasSuffix predicate on the "pattern" field.
func PatternHasSuffix(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldHasSuffix(FieldPattern, v))
}

// PatternEqualFold applies the EqualFold predicate on the "pattern" field.
func PatternEqualFold(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEqualFold(FieldPattern, v))
}

// PatternContainsFold applies the ContainsFold predicate on the "pattern" field.
func PatternContainsFold(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldContainsFold(FieldPattern, v))
}

// PatternTypeEQ applies the EQ predicate on the "pattern_type" field.
func PatternTypeEQ(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEQ(FieldPatternType, v))
}

// PatternTypeNEQ applies the NEQ predicate on the "pattern_type" field.
func PatternTypeNEQ(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldNEQ(FieldPatternType, v))
}

// PatternTypeIn applies the In predicate on the "pattern_type" field.
func PatternTypeIn(vs ...string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldIn(FieldPatternType, vs...))
}

// PatternTypeNotIn applies the NotIn predicate on the "pattern_type" field.
func PatternTypeNotIn(vs ...string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldNotIn(FieldPatternType, vs...))
}

// PatternTypeGT applies the GT predicate on the "pattern_type" field.
func PatternTypeGT(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldGT(FieldPatternType, v))
}

// PatternTypeGTE applies the GTE predicate on the "pattern_type" field.
func PatternTypeGTE(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldGTE(FieldPatternType, v))
}

// PatternTypeLT applies the LT predicate on the "pattern_type" field.
func PatternTypeLT(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldLT(FieldPatternType, v))
}

// PatternTypeLTE applies the LTE predicate on the "pattern_type" field.
func PatternTypeLTE(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldLTE(FieldPatternType, v))
}

// PatternTypeContains applies the Contains predicate on the "pattern_type" field.
func PatternTypeContains(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldContains(FieldPatternType, v))
}

// PatternTypeHasPrefix applies the HasPrefix predicate on the "pattern_type" field.
func PatternTypeHasPrefix(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldHasPrefix(FieldPatternType, v))
}

// PatternTypeHasSuffix applies the HasSuffix predicate on the "pattern_type" field.
func PatternTypeHasSuffix(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldHasSuffix(FieldPatternType, v))
}

// PatternTypeEqualFold applies the EqualFold predicate on the "pattern_type" field.
func PatternTypeEqualFold(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEqualFold(FieldPatternType, v))
}

// PatternTypeContainsFold applies the ContainsFold predicate on the "pattern_type" field.
func PatternTypeContainsFold(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldContainsFold(FieldPatternType, v))
}

// SeverityEQ applies the EQ predicate on the "severity" field.
func SeverityEQ(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEQ(FieldSeverity, v))
}

// SeverityNEQ applies the NEQ predicate on the "severity" field.
func SeverityNEQ(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldNEQ(FieldSeverity, v))
}

// SeverityIn applies the In predicate on the "severity" field.
func SeverityIn(vs ...string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldIn(FieldSeverity, vs...))
}

// SeverityNotIn applies the NotIn predicate on the "severity" field.
func SeverityNotIn(vs ...string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldNotIn(FieldSeverity, vs...))
}

// SeverityGT applies the GT predicate on the "severity" field.
func SeverityGT(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldGT(FieldSeverity, v))
}

// SeverityGTE applies the GTE predicate on the "severity" field.
func SeverityGTE(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldGTE(FieldSeverity, v))
}

// SeverityLT applies the LT predicate on the "severity" field.
func SeverityLT(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldLT(FieldSeverity, v))
}

// SeverityLTE applies the LTE predicate on the "severity" field.
func SeverityLTE(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldLTE(FieldSeverity, v))
}

// SeverityContains applies the Contains predicate on the "severity" field.
func SeverityContains(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldContains(FieldSeverity, v))
}

// SeverityHasPrefix applies the HasPrefix predicate on the "severity" field.
func SeverityHasPrefix(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldHasPrefix(FieldSeverity, v))
}

// SeverityHasSuffix applies the HasSuffix predicate on the "severity" field.
func SeverityHasSuffix(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldHasSuffix(FieldSeverity, v))
}

// SeverityEqualFold applies the EqualFold predicate on the "severity" field.
func SeverityEqualFold(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEqualFold(FieldSeverity, v))
}

// SeverityContainsFold applies the ContainsFold predicate on the "severity" field.
func SeverityContainsFold(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldContainsFold(FieldSeverity, v))
}

// ActionEQ applies the EQ predicate on the "action" field.
func ActionEQ(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEQ(FieldAction, v))
}

// ActionNEQ applies the NEQ predicate on the "action" field.
func ActionNEQ(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldNEQ(FieldAction, v))
}

// ActionIn applies the In predicate on the "action" field.
func ActionIn(vs ...string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldIn(FieldAction, vs...))
}

// ActionNotIn applies the NotIn predicate on the "action" field.
func ActionNotIn(vs ...string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldNotIn(FieldAction, vs...))
}

// ActionGT applies the GT predicate on the "action" field.
func ActionGT(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldGT(FieldAction, v))
}

// ActionGTE applies the GTE predicate on the "action" field.
func ActionGTE(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldGTE(FieldAction, v))
}

// ActionLT applies the LT predicate on the "action" field.
func ActionLT(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldLT(FieldAction, v))
}

// ActionLTE applies the LTE predicate on the "action" field.
func ActionLTE(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldLTE(FieldAction, v))
}

// ActionContains applies the Contains predicate on the "action" field.
func ActionContains(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldContains(FieldAction, v))
}

// ActionHasPrefix applies the HasPrefix predicate on the "action" field.
func ActionHasPrefix(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldHasPrefix(FieldAction, v))
}

// ActionHasSuffix applies the HasSuffix predicate on the "action" field.
func ActionHasSuffix(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldHasSuffix(FieldAction, v))
}

// ActionEqualFold applies the EqualFold predicate on the "action" field.
func ActionEqualFold(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEqualFold(FieldAction, v))
}

// ActionContainsFold applies the ContainsFold predicate on the "action" field.
func ActionContainsFold(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldContainsFold(FieldAction, v))
}

// MaskContentEQ applies the EQ predicate on the "mask_content" field.
func MaskContentEQ(v bool) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEQ(FieldMaskContent, v))
}

// MaskContentNEQ applies the NEQ predicate on the "mask_content" field.
func MaskContentNEQ(v bool) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldNEQ(FieldMaskContent, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldNEQ(FieldEnabled, v))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v int) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v int) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...int) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...int) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v int) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v int) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v int) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v int) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldLTE(FieldPriority, v))
}

// ScopeEQ applies the EQ predicate on the "scope" field.
func ScopeEQ(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEQ(FieldScope, v))
}

// ScopeNEQ applies the NEQ predicate on the "scope" field.
func ScopeNEQ(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldNEQ(FieldScope, v))
}

// ScopeIn applies the In predicate on the "scope" field.
func ScopeIn(vs ...string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldIn(FieldScope, vs...))
}

// ScopeNotIn applies the NotIn predicate on the "scope" field.
func ScopeNotIn(vs ...string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldNotIn(FieldScope, vs...))
}

// ScopeGT applies the GT predicate on the "scope" field.
func ScopeGT(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldGT(FieldScope, v))
}

// ScopeGTE applies the GTE predicate on the "scope" field.
func ScopeGTE(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldGTE(FieldScope, v))
}

// ScopeLT applies the LT predicate on the "scope" field.
func ScopeLT(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldLT(FieldScope, v))
}

// ScopeLTE applies the LTE predicate on the "scope" field.
func ScopeLTE(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldLTE(FieldScope, v))
}

// ScopeContains applies the Contains predicate on the "scope" field.
func ScopeContains(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldContains(FieldScope, v))
}

// ScopeHasPrefix applies the HasPrefix predicate on the "scope" field.
func ScopeHasPrefix(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldHasPrefix(FieldScope, v))
}

// ScopeHasSuffix applies the HasSuffix predicate on the "scope" field.
func ScopeHasSuffix(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldHasSuffix(FieldScope, v))
}

// ScopeEqualFold applies the EqualFold predicate on the "scope" field.
func ScopeEqualFold(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEqualFold(FieldScope, v))
}

// ScopeContainsFold applies the ContainsFold predicate on the "scope" field.
func ScopeContainsFold(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldContainsFold(FieldScope, v))
}

// ModelsEQ applies the EQ predicate on the "models" field.
func ModelsEQ(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEQ(FieldModels, v))
}

// ModelsNEQ applies the NEQ predicate on the "models" field.
func ModelsNEQ(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldNEQ(FieldModels, v))
}

// ModelsIn applies the In predicate on the "models" field.
func ModelsIn(vs ...string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldIn(FieldModels, vs...))
}

// ModelsNotIn applies the NotIn predicate on the "models" field.
func ModelsNotIn(vs ...string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldNotIn(FieldModels, vs...))
}

// ModelsGT applies the GT predicate on the "models" field.
func ModelsGT(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldGT(FieldModels, v))
}

// ModelsGTE applies the GTE predicate on the "models" field.
func ModelsGTE(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldGTE(FieldModels, v))
}

// ModelsLT applies the LT predicate on the "models" field.
func ModelsLT(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldLT(FieldModels, v))
}

// ModelsLTE applies the LTE predicate on the "models" field.
func ModelsLTE(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldLTE(FieldModels, v))
}

// ModelsContains applies the Contains predicate on the "models" field.
func ModelsContains(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldContains(FieldModels, v))
}

// ModelsHasPrefix applies the HasPrefix predicate on the "models" field.
func ModelsHasPrefix(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldHasPrefix(FieldModels, v))
}

// ModelsHasSuffix applies the HasSuffix predicate on the "models" field.
func ModelsHasSuffix(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldHasSuffix(FieldModels, v))
}

// ModelsIsNil applies the IsNil predicate on the "models" field.
func ModelsIsNil() predicate.DLPRule {
	return predicate.DLPRule(sql.FieldIsNull(FieldModels))
}

// ModelsNotNil applies the NotNil predicate on the "models" field.
func ModelsNotNil() predicate.DLPRule {
	return predicate.DLPRule(sql.FieldNotNull(FieldModels))
}

// ModelsEqualFold applies the EqualFold predicate on the "models" field.
func ModelsEqualFold(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEqualFold(FieldModels, v))
}

// ModelsContainsFold applies the ContainsFold predicate on the "models" field.
func ModelsContainsFold(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldContainsFold(FieldModels, v))
}

// MetadataEQ applies the EQ predicate on the "metadata" field.
func MetadataEQ(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEQ(FieldMetadata, v))
}

// MetadataNEQ applies the NEQ predicate on the "metadata" field.
func MetadataNEQ(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldNEQ(FieldMetadata, v))
}

// MetadataIn applies the In predicate on the "metadata" field.
func MetadataIn(vs ...string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldIn(FieldMetadata, vs...))
}

// MetadataNotIn applies the NotIn predicate on the "metadata" field.
func MetadataNotIn(vs ...string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldNotIn(FieldMetadata, vs...))
}

// MetadataGT applies the GT predicate on the "metadata" field.
func MetadataGT(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldGT(FieldMetadata, v))
}

// MetadataGTE applies the GTE predicate on the "metadata" field.
func MetadataGTE(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldGTE(FieldMetadata, v))
}

// MetadataLT applies the LT predicate on the "metadata" field.
func MetadataLT(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldLT(FieldMetadata, v))
}

// MetadataLTE applies the LTE predicate on the "metadata" field.
func MetadataLTE(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldLTE(FieldMetadata, v))
}

// MetadataContains applies the Contains predicate on the "metadata" field.
func MetadataContains(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldContains(FieldMetadata, v))
}

// MetadataHasPrefix applies the HasPrefix predicate on the "metadata" field.
func MetadataHasPrefix(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldHasPrefix(FieldMetadata, v))
}

// MetadataHasSuffix applies the HasSuffix predicate on the "metadata" field.
func MetadataHasSuffix(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldHasSuffix(FieldMetadata, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.DLPRule {
	return predicate.DLPRule(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.DLPRule {
	return predicate.DLPRule(sql.FieldNotNull(FieldMetadata))
}

// MetadataEqualFold applies the EqualFold predicate on the "metadata" field.
func MetadataEqualFold(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEqualFold(FieldMetadata, v))
}

// MetadataContainsFold applies the ContainsFold predicate on the "metadata" field.
func MetadataContainsFold(v string) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldContainsFold(FieldMetadata, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v int64) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v int64) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...int64) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...int64) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v int64) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v int64) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v int64) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v int64) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.DLPRule {
	return predicate.DLPRule(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.DLPRule {
	return predicate.DLPRule(sql.FieldNotNull(FieldCreatedBy))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.DLPRule {
	return predicate.DLPRule(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DLPRule) predicate.DLPRule {
	return predicate.DLPRule(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DLPRule) predicate.DLPRule {
	return predicate.DLPRule(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DLPRule) predicate.DLPRule {
	return predicate.DLPRule(sql.NotPredicates(p))
}
